### ISSUE TITLE
Show custom action for specific model only

### ISSUE THREAD

**Issue by JohnGoodman** [railsadminteam/rails_admin#1004]
Hey All,

I wrote a custom action for my rails_admin app. I only want this action to show on in the list view of a specific model. I was finally able to achieve this by adding the action name to the default action list like so:

```
config.actions do
  # root actions
  dashboard                     # mandatory
  # collection actions
  index                         # mandatory
  new
  export
  history_index
  bulk_delete
  # member actions
  show
  edit
  delete
  history_show
  show_in_app
  duplicate_program # This is the custom action
end
```

In my rails_admin_duplicate_program.rb file, I set the visibility like this:

```
register_instance_option :visible do
      bindings[:object].class.name.downcase == 'program'
 end
```

Gists of these files are here:
https://gist.github.com/1894506
https://gist.github.com/1894513

My question is, is there a better way to only show a custom action for a specified model? 

Thanks.

**Comment by ankita14** [comment]
Thanks bbenezech!

**Comment by Zlatov** [comment]
Does this not work for me, due to rails_admin 1.4.2 version?

```ruby
RailsAdmin.config do |config|
  RailsAdmin::Config::Actions.register(RailsAdmin::Config::Actions::WhoHere)
...
  config.actions do
    who_here do
      only Market::Model::Angar
    end
  end
end
```

The action renders successfully in every model.

I could enforce the constraint myself if I had access to the config at this point:

```rb
module RailsAdmin
  module Config
    module Actions
      class WhoHere < RailsAdmin::Config::Actions::Base
        register_instance_option :visible? do
          config.actions.who_here.only.include? bindings[:abstract_model].model_name
```

I can’t understand if it is possible to access the configuration in this place and how.
