### ISSUE TITLE
'Select all' checkbox should select all instances checkboxes

### ISSUE THREAD

**Issue by versilov** [railsadminteam/rails_admin#1010]
Like in GMail, for example.

For now the functionality of checkbox in the table header of the index view is not clear for a new user. If it will mark all instances checkboxes as checked, than it's function will be obvious for everyone.

**Comment by pandaiolo** [comment]
> a contextual message to select ALL items (including the one not displayed, like Gmail does)

@bbenezech sorry to bump that very old issue, but I just wanted to make sure that this is not implemented? The "global" checkbox just checks the individual checkboxes on the pages, right? Could the real "select all" feature be implemented? Any advice? PR welcome?

**Comment by caboteria** [comment]
Hi, sorry I can't be helpful but I haven't used rails_admin in quite a few years.
