### ISSUE TITLE
Ability to hide the Filter feature

### ISSUE THREAD

**Issue by dogweather** [railsadminteam/rails_admin#1071]
Our use case: Our client uses rails_admin to manage a list of five users. The 'Add filter', 'Filter' input box, and 'Refresh' button are all extra visual distraction that will never be used.

Solution: Expose a config setting to disable & hide the Filter feature per-model or app-wide.

**Comment by VladislavShved** [comment]
`module RailsAdmin::NonFilterable

  extend ActiveSupport::Concern

  included do
    rails_admin do
      model_class = self.abstract_model.model_name.constantize
      model_class.column_names.each do |column|

        if model_class.try(:enable_filter_for).present? && model_class.enable_filter_for.include?(column.to_sym)
          code = "field :#{column.to_sym} do \r\n searchable [:#{column.to_sym}] \r\n queryable true \r\n filterable true \r\n end"
        else
          code = "field :#{column.to_sym} do \r\n searchable [] \r\n queryable false \r\n filterable false \r\n end"
        end

        eval(code)
      end
    end
  end

end`

then

`include RailsAdmin::NonFilterable`

**Comment by VladislavShved** [comment]
```
module RailsAdmin::NonFilterable

  extend ActiveSupport::Concern

  included do
    rails_admin do
      model_class = self.abstract_model.model_name.constantize
      model_class.column_names.each do |column|

        if model_class.try(:enable_filter_for).present? && model_class.enable_filter_for.include?(column.to_sym)
          code = "field :#{column.to_sym} do \r\n searchable [:#{column.to_sym}] \r\n queryable true \r\n filterable true \r\n end"
        else
          code = "field :#{column.to_sym} do \r\n searchable [] \r\n queryable false \r\n filterable false \r\n end"
        end

        eval(code)
      end
    end
  end

end
