### ISSUE TITLE
Create custom sections/pages

### ISSUE THREAD

**Issue by drale2k** [railsadminteam/rails_admin#1077]
Is it possible to create custom pages/sections in rails admin? I need a page to show some statistics and to have some buttons which would trigger some actions on clients. Pretty random but simple stuff, i am not sure how to do something like this with Rails Admin.

**Comment by dmitrypol** [comment]
Sorry if it's silly question.  I know how to create custom actions and I can store partials in app/views/rails_admin.  

But how do I get a specific page to load via URL like http://localhost:3000/admin/my_page?  I can put my_page.html.haml in app/views/rails_admin but how do I link to it from the navbar?  Do I need to create custom controller?
