### ISSUE TITLE
Is present and Is blank filter

### ISSUE THREAD

**Issue by kweejibow** [railsadminteam/rails_admin#1099]
Apologies in advance I'm quite new to rails and rails_admin.

Seem like the 'Is Present' and 'Is blank' column filters fail for any boolean value

It also fails when checking against the integer value of a FK object. 

To better explain: I have a relationship between Client and Appointment, in my appointment list I include the field :client <-- where some automagick seems to display the clients name and create a link to that object. I can use all the other filters on the :client field just fine but if i try and check on Is Present or Is Blank the sql generated seems to try and check if client_id is not null and client_id != '' <-- which I believe is the issue.

Thanks!

**Comment by nlsrchtr** [comment]
This is still relevant in `0.6.7`. Is there some work going into the Postgres specifics?

**Comment by coorasse** [comment]
This error still exists. please reopen the issue.

**Comment by jhilden** [comment]
also still having the issue with `0.6.8`

**Comment by SuperMasterBlasterLaser** [comment]
This still exists on `0.8.1`

**Comment by Hasan-a-ayar** [comment]
No fix yet? Same issue exists with 0.8.1
