### ISSUE TITLE
Add support for Draper

### ISSUE THREAD

**Issue by xto** [railsadminteam/rails_admin#1162]
I'm using RailsAdmin for my project and I want to keep some presentation details out of my model using Draper.

Unfortunately, there's no way to use the decorator in the RailsAdmin configuration, or at least, I haven't seen it.

Is there a way to configure a field to be a method call on another object? Right now I have it has an `ActiveRecord::Base#delegate` but it still forces me to expose a presentation concern in my model.

Something along the lines of:

``` ruby
config.model User do |user|
  list do
    field :full_name do
      UserDecorator.decorate(user).full_name
    do
  do
end
```

**Comment by dmitrypol** [comment]
+1.  Worked for me
