### ISSUE TITLE
sort_reverse doesn't  work

### ISSUE THREAD

**Issue by kor6n** [railsadminteam/rails_admin#1181]
Using latest rails_admin from gem 'rails_admin', :git => 'https://github.com/sferik/rails_admin.git'

``` ruby
  config.model Post do
    list do
      sort_by :weight
      sort_reverse false # or true anyway sorting goes ASC
      exclude_fields :created_at, :updated_at
    end
    weight 203
  end
```

**Comment by mdkirby** [comment]
@adriansalceanu - It looks like what rails admin is doing is equivalent to 
```"#{table_name}.#{YOUR_INPUT.to_s} desc"```
Adding the following, and leaving off the last ASC working for me:
```
list do
  sort_reverse false
  sort_by 'event_id DESC, position'
end
```
