### ISSUE TITLE
Postgresql array column

### ISSUE THREAD

**Issue by dexion** [railsadminteam/rails_admin#1218]
I use array column in my database. So, i give following:

```
RuntimeError (Unsupported field datatype: integer_array):
```

Also, for supporting this postresql types I use gem

```
gem 'activerecord-postgres-array', :git => 'https://github.com/tlconnor/activerecord-postgres-array.git'
```

What do I do?

**Comment by michaelimstepf** [comment]
@lieldulev You're a legend, thanks!

**Comment by robotfelix** [comment]
An alternative solution is to configure the field to use rails_admin's in-built JSON column support.

    # For example:
    configure(:my_array_column, :json)

It's not very forgiving when the JSON provided is something other than a flat array (throwing an exception in this case), but otherwise seems to work perfectly fine. Note that I've only tested it on integer and string arrays.

**Comment by MattGo** [comment]
Very helpful hint. Thanks! Any idea on how to make this array representation as a string to be searchable with a pg LIKE statement? Cheers.

**Comment by subelsky** [comment]
This is what we use for `hstore`; we override the render method of the field on the edit screen so that the YAML can be edited with the ACE editor. But this should help you get started.

```ruby
# config/initializers/rails_admin_pg_hstore.rb
require "yaml"

# adapted from https://github.com/sferik/rails_admin/issues/1218
class RailsAdminPgHstore < RailsAdmin::Config::Fields::Base
  register_instance_option :formatted_value do
    value.to_yaml
  end

  def parse_input(params)
    params[name] = if params[name].blank?
                     nil
                   else
                     YAML.load(params[name])
                   end
  end
end

RailsAdmin::Config::Fields::Types::register(:pg_hstore,RailsAdminPgHstore)
```
use it like this:
```ruby
edit do
  field :options, :pg_hstore
end
```

**Comment by dhirajbajaj** [comment]
rails_admin do
    configure :array_column, :pg_int_array
end

**Comment by anklos** [comment]
@lieldulev solution is great, thanks a lot!

just a small issue when you create new record it would through exception as it tries to join `nil`. so you could simple update the first bit code like below:

```ruby
class RailsAdminPgArray < RailsAdmin::Config::Fields::Base
  register_instance_option :formatted_value do
    value.join(',') if value
  end
end
```

**Comment by fedeest** [comment]
@lieldulev Hi, I'm sorry for coming with after suck a long time, but I'm understanding how to make your solution work.

I've added the rails_admin_pg_arrays.rb to the initializers folder. But I don't understand where to put this:
```
rails_admin do
  edit do
    field :field_name, :pg_int_array
  end
end
```

**Comment by lieldulev** [comment]
@fedeest - In the model definition...

Look at the 2nd example in the following link -

https://github.com/sferik/rails_admin/wiki/Models

**Comment by fedeest** [comment]
@lieldulev thank you, I can see it now, but one more little thing:

On the model that I included that, I can ONLY edit the :pg_int_array. I need to have all other fields as well.

**Comment by lieldulev** [comment]
@fedeest - Not sure I understand the issue,

But take a look at "Dirty" example in the below wiki -

https://github.com/sferik/rails_admin/wiki/How-to:-Reloading-RailsAdmin-Config-Automatically

**Comment by fedeest** [comment]
@lieldulev here, let me explain:

On the rails_admin edit view for my model (which has the :pg_int_array and to which I included those lines of code) instead of it showing all the fields of the model, it only shows the :pg_int_array field.
If you still don't understand I'll attach some screenshots.

**Comment by lieldulev** [comment]
If I understand correctly this comment (on this thread) should help you:

https://github.com/sferik/rails_admin/issues/1218#issuecomment-50916320

(tl;dr - just add all the fields)

**Comment by fedeest** [comment]
@lieldulev hi again. I have more issue with this. In my model I have many `has_many` associations, some with `accepts_nested_attributes_for` and one `has_and_belongs_to_many`association too.

My last question would be how to represent these in the rails_admin view so that it shows them as they are by default (as the image shows).
![screenshot from 2016-05-23 09 52 00](https://cloud.githubusercontent.com/assets/17027853/15471396/1f247270-20cc-11e6-924f-1ccc324e2454.png)

**Comment by grillermo** [comment]
I did a small gist with an array field implementation
https://gist.github.com/grillermo/58fa08e0d288db069fb998e5a2e3961d
For future interested people

**Comment by idknox** [comment]
I had a similar problem with a datetime array and solved using a custom partial and creating an input for each item in the array.

**Comment by haroldus-** [comment]
@anklos pretty value option is needed if the default value of the column is an empty array `[]` (as opposed to just `nil`

```ruby
class RailsAdminPgArray < RailsAdmin::Config::Fields::Base
  register_instance_option :formatted_value do
    value.join(',') if value.presence
  end
  register_instance_option :pretty_value do
    formatted_value.presence || ' - '
  end
end
```

**Comment by gustavo-iha** [comment]
> An alternative solution is to configure the field to use rails_admin's in-built JSON column support.
> 
> ```
> # For example:
> configure(:my_array_column, :json)
> ```
> 
> It's not very forgiving when the JSON provided is something other than a flat array (throwing an exception in this case), but otherwise seems to work perfectly fine. Note that I've only tested it on integer and string arrays.

That's a great solution. Simple and fast! ;)
