### ISSUE TITLE
Paging throws exception when config.model is used (with mongoid)

### ISSUE THREAD

**Issue by cloudify** [railsadminteam/rails_admin#1232]
Hi there,
It's been a full day I'm trying to debug an annoying issue with a brand new rails 3.2.6 app with mongoid 2.4.11 and rails_admin 0.5.0:

I have just two models (`User` and `Role`), with the default rails_admin config everything works fine but as soon as I try to customize the appearance of the `User` model with:

```
config.model User do
end
```

in the `rails_admin.rb` config, when I try browse the user model at `/admin/user` a `NoMethodError` exception is thrown:

```
NoMethodError (undefined method `page' for #<Array:0x00000127a38dd8>):
  mongoid (2.4.11) lib/mongoid/criteria.rb:385:in `method_missing'
  kaminari (0.13.0) lib/kaminari/models/mongoid_extension.rb:11:in `page'
  rails_admin (0.0.5) lib/rails_admin/adapters/mongoid.rb:46:in `all'
  rails_admin (0.0.5) app/controllers/rails_admin/main_controller.rb:131:in `get_collection'
  rails_admin (0.0.5) app/controllers/rails_admin/main_controller.rb:39:in `list_entries'
  rails_admin (0.0.5) lib/rails_admin/config/actions/index.rb:30:in `block (2 levels) in <class:Index>'
```

if I remove the `config.model` entry, everything works fine, I can browse all models and all records.
Any idea?

**Comment by h8rry** [comment]
I am using the latest Mongoid and getting the error `NoMethodError - undefined method `paginate'` when going into any model page.

**Comment by simonv3** [comment]
@h8rry are you using the karimani-mongoid gem?

**Comment by h8rry** [comment]
@simonv3 Yes. I was using `Kaminari-mongoid`. It works now that I've removed it. Thank you!

**Comment by simonv3** [comment]
Yeah, I'm not sure if this qualifies as a bug in Kaminari-mongoid or in rails_admin.
