### ISSUE TITLE
Other custom text editors? (markdown via MarkItUp)

### ISSUE THREAD

**Issue by Tuckie** [railsadminteam/rails_admin#1235]
After seeing the codemirror pull: https://github.com/sferik/rails_admin/pull/1164 I was wondering how difficult it would be to add other client side editors into rails admin? 

I'm looking at incorporating markdown support into my application, but a little extra assistance via MarkItUp is probably going to  be needed.

https://www.ruby-toolbox.com/gems/markitup_rails3
http://markitup.jaysalvat.com/home/

Looking at code changes that was required, it doesn't appear to be very modular.  Is there a better way to cleanly integrate different editors (maybe just as a markdown field type)?

**Comment by Ryo10Leo** [comment]
hhhh****

jjj__
