### ISSUE TITLE
add "unscoped" mode to "model config"

### ISSUE THREAD

**Issue by ideomix** [railsadminteam/rails_admin#1348]
I want to add a "unscoped" mode to "model config".
I also read the entry in the past, such a way as to create a subclass is difficult to accept.
To "model config" section of the "raid_admin.rb" simple, strongly desired a solution that can be configured as "unscoped = true".

What everyone think?

**Comment by cassidyclawson** [comment]
+ 1 

Just another vote for this feature.

**Comment by dmitrypol** [comment]
+1

**Comment by mshibuya** [comment]
In fact, this can already be achieved by list scope configuration(added by #1861).
```ruby
RailsAdmin.config do |config|
  config.model Player do
    list do
      scopes [:unscoped]
    end
  end
end
```

**Comment by mshibuya** [comment]
As is stated in https://github.com/sferik/rails_admin/pull/2428#issuecomment-147064737, above solution only works for list view.
I'll try to work this out...

**Comment by dmitrypol** [comment]
When using RailsAdmin 0.7.0 with Mongoid (4 and 5) I get this error when accessing http://localhost:3000/admin/user?model_name=user&scope=unscoped

Here is my RA config:
    config.model 'User' do
      list do      
        scopes  [nil, :unscoped]
      end
    end

gems/ruby-2.0.0-p594/gems/rails_admin-0.7.0/app/views/rails_admin/main/index.html.haml where line #154 raised:

nil can't be coerced into Float
Extracted source (around line #26):
      count_without_padding = 0 if count_without_padding < 0

26      total_pages_count = (count_without_padding.to_f / limit_value).ceil
      if max_pages.present? && max_pages < total_pages_count
        max_pages
      else

**Comment by dburt** [comment]
@mshibuya please let me know if you can use my help. For example, if my pull request is not too far off functionally, you could show me what you want the DSL to look like, and I would be happy to change my implementation and create another pull request.

**Comment by jszwedko** [comment]
Any update on this? #2586 looks compelling.

**Comment by Otterpocket** [comment]
Was this resolved somewhere else? #2586 is still not merged

**Comment by dfabreguette-ap** [comment]
I still have the same issue with latest version of mongoid & RailsAdmin :
rails_admin (2.2.1)
mongoid (7.3.3)

"unscoped" call removes all pagination filters in the Mongoid Criteria object.
Any idea how I can fix this as we use "default_scopes" on many rails models in our app, affecting default sorts.
As a result, sorting is simply not working in rails admin because of those default scopes.

I assume the best option for us would be to feed RailsAdmin a default "MyModel.unscoped" object which gets prepared with pagination and other filters.
Has someone got the same problem ?

**Comment by canted** [comment]
I had the same issue as @dfabreguette and resolved it using [unscope](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-unscope) instead of `unscoped`
