### ISSUE TITLE
Rake db:migrate errors

### ISSUE THREAD

**Issue by tayfunylmaz** [railsadminteam/rails_admin#1362]
Hi, 

 I use to rails 3.2.1 with mysql adapter, I install rails_admin then I see this errors made "rake db:migrate", "[RailsAdmin] RailsAdmin initialization disabled by default. Pas SKIP_RAILS_INITIALIZER=false if you need it." 
Rails_admin is work. I visited '/admin' then show dashboard panel.

Thanks.
taifunylmaz.

**Comment by hut8** [comment]
I installed the gem yesterday and now I get this message on every migration and probably every time I run `rake`. I don't understand what it even means.
