### ISSUE TITLE
undefined local variable or method `_hamlout'

### ISSUE THREAD

**Issue by treyconnell** [railsadminteam/rails_admin#1408]
Should I be seeing errors like this in the log?

shared/bundle/ruby/1.9.1/gems/haml-3.1.7/lib/haml/helpers.rb:543 - undefined local variable or method `_hamlout' for #<#Class:0x00000007763ef8:0x00000007b3b440>

Thanks!
Trey

**Comment by amolplay** [comment]
Same error appearing ...tried multiple solutions but didn't found ....

Any help will be appreciated...

Exception `NameError' at /.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:181 - undefined local variable or method `_hamlout' for #<#<Class:0x005576c2fb31a8>:0x005576c71fed28>

Exception `NameError' at /.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/helpers.rb:543 - undefined local variable or method `_hamlout' for #<#<Class:0x005576c2fb31a8>:0x005576c71fed28>

Exception `NoMethodError' at /app/views/devise/sessions/new.html.haml:10 - undefined method `control_group' for #<ActionView::Helpers::FormBuilder:0x005576c73291a8>
