### ISSUE TITLE
undefined method `per' for #<ActiveRecord::Relation:0x007fc43bcc65a8>

### ISSUE THREAD

**Issue by bruceyue** [railsadminteam/rails_admin#1420]
When I click a model name, it showed the error "undefined method `per' for #ActiveRecord::Relation:0x007fc43bcc65a8". Thanks for your help.

**Comment by RajRoR** [comment]
This helped me: http://tech-brains.blogspot.in/2012/11/kaminari-willpaginate-incompatibility.html
