### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by ai** [railsadminteam/rails_admin#1443]
Ruby on Rails 4 is now beta and will be released very soon.

It will be nice, if RailsAdmin will support Rails 4.

Now RailsAdmin is locked on `rails ~> 3.1`. Is it code dependency, which need real strong refactoring?

**Comment by davidwparker** [comment]
Note that the wiki docs are _really_ old. This page https://github.com/sferik/rails_admin/wiki/CarrierWave still uses `attr_accessible`. It would be nice to know what the current methodology for deleting an image is in Rails 4+. Cheers!
