### ISSUE TITLE
undefined method `per' for #<ActiveRecord::Relation:0x00000004450408>

### ISSUE THREAD

**Issue by kashiftufail** [railsadminteam/rails_admin#1498]
Hi i have theses versions of my gems.

rails_admin (0.0.5)
kaminari (0.12.4)
will_paginate(3.0.4)

I try this https://github.com/sferik/rails_admin/wiki/Troubleshoot

```
    Conflict between will_paginate and kaminari
```

but same error occurs

**Comment by RajRoR** [comment]
Got a blog that may help: http://goo.gl/zSNULO

**Comment by taniarv** [comment]
For me, it was an incompatibility with will_paginate, it seems you can't have both installed. Just uninstalled will_paginate and it works!
