### ISSUE TITLE
Using "open" as a field name breaks edit template

### ISSUE THREAD

**Issue by mgartner** [railsadminteam/rails_admin#1536]
When I create a boolean field called `:open`, I get the following error when trying to edit the model. I saw #436 which may be related, but it says it was fixed about 2 years ago, so maybe it has been broken again since the fix.

`wrong number of arguments (0 for 1..3)`

`1: = form.send field.view_helper, field.method_name, field.html_attributes.reverse_merge((hdv = field.html_default_value).nil? ? {} : { :value => hdv, :checked => hdv })
`

Full Trace:
https://gist.github.com/mgartner/5015874

**Comment by codealchemy** [comment]
I've tried adding a test for this (https://github.com/codealchemy/rails_admin/commit/6f881149ca1976de8408d0f7cbd123eca330b022) but everything appears to be passing, are there any additional reproduction steps for this issue (the linked trace is a 404)?

**Comment by mshibuya** [comment]
@codealchemy Then could you open a PR with the test you wrote?
Let's merge it and consider this issue to be resolved.
