### ISSUE TITLE
Replacing the datepicker with bootstrap-datepicker

### ISSUE THREAD

**Issue by jasonm23** [railsadminteam/rails_admin#1551]
http://www.eyecon.ro/bootstrap-datepicker/ 

(improved in this fork.)

https://github.com/eternicode/bootstrap-datepicker

It would be good if the old JQueryUI datepicker was replaced with the bootstrap-datepicker, I am currently looking at this in the source, and will issue a pull request if I get it working.

I'm posting this in case anyone else is already working on this / or has thoughts.

**Comment by dalpo** [comment]
https://github.com/sferik/rails_admin/pull/2391
