### ISSUE TITLE
How to configure disabling load has_many association on show and edit.

### ISSUE THREAD

**Issue by Curter29** [railsadminteam/rails_admin#1574]
I have Client and Message, on client has_many message, and if client has 1 Million message rails_admin, try to load all 1M, how to disable load in this case?

I read Wiki and don't find any solution (

**Comment by jeromedalbert** [comment]
I have a similar issue where I wanted to disable has_many :through associations because most of them were taking a long time to load on my app. But I wanted to disable for all admin pages, without having to write `exclude_fields` everywhere.

So I came up with the following hack:

```ruby
# config/initializers/rails_admin.rb

# Monkey patch to hide all has_many :through associations for faster page loads
module RailsAdmin
  module Config
    module Fields
      module Types
        class HasManyAssociation
          register_instance_option :visible? do
            @visible ||= !association.options[:through] && !associated_model_config.excluded?
          end
        end
      end
    end
  end
end
```

This may be an edge-case but I am posting this in case someone finds it useful.

**Comment by Wusinho** [comment]
> I had a similar issue where I wanted to disable has_many :through associations because they were taking a long time to load in my app. But I wanted to disable them globally without having to write `exclude_fields` everywhere.
> 
> So I came up with the following hack:
> 
> ```ruby
> # config/initializers/rails_admin.rb
> 
> # Monkey patch to hide all has_many :through associations for faster page loads
> module RailsAdmin
>   module Config
>     module Fields
>       module Types
>         class HasManyAssociation
>           register_instance_option :visible? do
>             @visible ||= !association.options[:through] && !associated_model_config.excluded?
>           end
>         end
>       end
>     end
>   end
> end
> ```
> 
> I find this useful because has_many :through associations perform slow table joins that can get even slower if you have many records. And most of the time I don't need to see these kinds of associations: if I want to create one, I can always edit the join model/table directly. So having has_many :through globally disabled by default gives me a nice global performance boost while retaining most of the features I care about.

Where exactly do you place that code? It's not working for me

**Comment by jeromedalbert** [comment]
@Wusinho In a rails initializer like config/initializers/rails_admin.rb

**Comment by kotsiuruba** [comment]
To hide has_many associations for all models:

`config/initializers/rails_admin.rb`
```
  RailsAdmin.config do |config|
    ActiveRecord::Base.descendants.each do |imodel|
      config.model "#{imodel.name}" do
        has_many_relations = imodel.reflections.select { |k, r| r.macro == :has_many }.keys.map(&:to_sym)
        list do
          exclude_fields *has_many_relations unless has_many_relations.blank?
        end
        show do
          exclude_fields *has_many_relations unless has_many_relations.blank?
        end
      end
    end
  end
```
