### ISSUE TITLE
rails_admin doesn't precompile assets:precompile for js or css on heroku

### ISSUE THREAD

**Issue by seifsallam** [railsadminteam/rails_admin#1633]
rails_admin precompiles all assets in `.../assets/rails_admin` except `.../assets/rails_admin/rails_admin.js` and `.../assets/rails_admin/rails_admin.css` 

For the admin page it is loaded as `/stylesheets/rails_admin/rails_admin.css` I tried 

``` ruby
config.assets.precompile += %w(rails_admin/rails_admin.css rails_admin/rails_admin.js)
```

But it doesn't work. I have another rails app and it worked by using the previous line, but it wasn't on heroku. Any ideas on where the problem is?

**Comment by williantenfen** [comment]
@seifsallam @Florian95  I copied the rails_admin.js into my project as well the .scss.erb, and all compiled fine.
