### ISSUE TITLE
Overriding js file inside another engine which RailsAdmin is embedded in

### ISSUE THREAD

**Issue by dfischer** [railsadminteam/rails_admin#1635]
When I view 

`/assets/rails_admin/custom/ui.js?body=1`

All I get is 

```
(function() {


}).call(this);
```

When I have a bunch of code in there. Is not not possible to override RailsAdmin inside another engine?

Structure is:
Core is the engine:

app/assets/javascripts/core 
app/assets/javascripts/rails_admin/custom/ui.js.erb

I created this "core" engine, and took everything common out of the main app into here and this is the only thing not working.

Overall, all I'm trying to do is `require_asset 'filepicker_v1'` which is in vendor/assets/javascripts/filepicker_v1.js but this doesn't seem to work once an engine is involved...

Edit to clarify after testing:

From parent app, including anything in engines path from engine/vendor/assets/javascripts works as long as it's not under another engine's namespace. 

`app/assets/javascripts/application.js` Does include anything from `engine/vendor/assets/javascripts`

`app/assets/javascripts/rails_admin/custom/ui.js.erb` Does not include anything from `engine/vendor/assets/javascripts`

**Comment by mshibuya** [comment]
Sounds like order issue, you need to make sure your custom JS is picked up before the RailsAdmin's one. Check your `Rails.application.config.assets.paths`.
