### ISSUE TITLE
Rails admin caching fields on production? (heroku)

### ISSUE THREAD

**Issue by dfischer** [railsadminteam/rails_admin#1652]
2013-05-22T00:03:59.341169+00:00 app[web.1]: ActionView::Template::Error (missing attribute: category):

I'm getting the above on a production instance on Heroku. I've always noticed if I go to the "new" view it shows an old field instead of the new field. How to refresh rails_admin's view of the schema? I deleted an old column and created a new but it's blowing up because of this on the edit view, and new view shows old fields. It is fully updated and migrated...

**Comment by jwgoh** [comment]
Any updates on this? Facing the same issue and running `heroku restart -a <app_name>` solves the problem

**Comment by kaiomagalhaes** [comment]
I've just faced the exact same issue, but it seems to be an intermittent one since in my Dev/QA servers it worked just fine, but broke in production.
