### ISSUE TITLE
custom_label_method not working with models in folders

### ISSUE THREAD

**Issue by shacker** [railsadminteam/rails_admin#1657]
I have custom_label_method working fine. Then I move the model into a subfolder, e.g. app/models/foo/bar.rb . I can then get rails_admin working again by adding to application.rb:

config.autoload_paths += %W(#{config.root}/app/models/foo)

All is well with rails_admin, but custom_label_method no longer works. I tried to fix it by tweaking config.model, e.g.:

  RailsAdmin.config do |config|
    config.model 'Bar:Mymodel' do

but no dice. It seems that custom_label_method can't be made to work with a model that lives in a subdir. Or am I missing something obvious? 

Thanks.

**Comment by mshibuya** [comment]
Codebase has changed a lot. Please reopen if you still have the issue.
