### ISSUE TITLE
Circular dependency detected while autoloading constant

### ISSUE THREAD

**Issue by alexandru-calinoiu** [railsadminteam/rails_admin#1697]
Hi,

I have a rails 4 project, with mongoid that mounts an grape api:

```
mount MyProject::API => '/'
```

When accessing `<site>/admin` I get the following exception:

```
RuntimeError (Circular dependency detected while autoloading constant Api):
```

When I remove the /app/api folder from autoload path all seems to work correctly (except the api of course)

Can you please give me some pointers for this issue?

**Comment by TangMonk** [comment]
I am using Grape with rails_admin, same issue
