### ISSUE TITLE
406 Error for Uploads on Associated Model

### ISSUE THREAD

**Issue by richardpeng** [railsadminteam/rails_admin#1698]
You get a 406 error when you have:
- two models connected by a has_many association (Book and Authors)
- the model belonging to the parent model has an upload field (Author.avatar)
- uploads are handled via Carrierwave
  
  do the following:
- go to the form to create a new record (Add new Book)
- add an instance of a has_many association (Add a new Author)
- attach a file (select a file for Author.avatar)
- submit the form

You get a '406 Not Acceptable' error and the record fails to be created.

**Comment by AlexKlim** [comment]
Very strange answer.. In console log, I see
```ruby
Parameters: {"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>nil}}}}}}}}}}}}}}, "model_name"=>"<my model name>"}
```
 if I upload image through popup and has_many association
