### ISSUE TITLE
Rails 4: wrong CKEditor asset path in production environment

### ISSUE THREAD

**Issue by focused** [railsadminteam/rails_admin#1706]
I add ckeditor field like this:

`field :content, :ck_editor`

In production environment it tries to load it from:
`assets/ckeditor/ckeditor.js`

I tried to add this line to production.rb:
`config.assets.precompile += %w(ckeditor/* ckeditor/init.js)`

But this does not work because you cannot have compiled asset file without digest in Rails 4 (in Rails 3.2 you still can), so it will never be found.

Rails admin should find this file with a digest (like `ckeditor-1dfg9852o3239sdf28234234.js`) in file name.

**Comment by ardeearam** [comment]
@billguy This works. Thanks! :)

**Comment by MrSena** [comment]
Rails.application.config.assets.precompile += %w( ckeditor/* )

**Comment by vitalyliber** [comment]
@MrSena Thanks. This works!
