### ISSUE TITLE
Filters broken with mongoid field alias

### ISSUE THREAD

**Issue by sepastian** [railsadminteam/rails_admin#1766]
I am using rails_admin with mongoid. When using mongoid's `:as` options, filters in rails_admin stop working.

For example, the following works as expected:

```
class A
    include Mongoid::Document
    field :long_name, :type => String
    rails_admin do
        list do
            filters [ :long_name ]
            field :long_name
        end
    end
end
```

While this does not:

```
class A
    include Mongoid::Document
    field :long_name, :as => :l, :type => String
    rails_admin do
        list do
            filters [ :long_name ]
            field :long_name
        end
    end
end
```

The name of the field has changed from `:long_name` to `:l`, `:long_name` is now stored in `field.options[:as]`. Mongoid maps between both names transparently, rails_admin does not. A workaround exists:

```
class A
    include Mongoid::Document
    field :long_name, :as => :l, :type => String
    rails_admin do
        list do
            filters [ :l ]
            field :l
        end
    end
end
```

For better readability and consistency with mongoid's behavior, rails_admin should   map between field names and aliases. It should be possible to use either the field name or the alias everywhere.

I would like to provide a pull request, if you can point me in the right direction. Is there a central place in rails_admin's mongoid adapter where field name resolution is taking place? Where should I start looking, or how would you go about improving this?

**Comment by mshibuya** [comment]
Dup of #1745.
