### ISSUE TITLE
"NoMethodError: undefined method `to_sym' for /.../i:Regexp" when filtering with this Mongoid model

### ISSUE THREAD

**Issue by tensiondriven** [railsadminteam/rails_admin#1795]
We're using Rails Admin + Mongoid and have one model that always causes this error when using the "filter" button.  To reproduce:

  1) visit [site]/admin/order
  2) enter any string in the "filter"
  3) click Refresh

Error: NoMethodError: undefined method `to_sym' for /.../i:Regexp

The model is named 'Order' and this only reproduces with this model, is it possible that the model name is being evaluated somewhere and mistaken for a db query?

I can provide a copy of the model code if desired.

This is a Rails 3 project on Ruby 2 with the following line in the Gemfile:

```
gem 'rails_admin'
```

Stack trace:

```
[PROJECT_ROOT]/vendor/bundle/ruby/2.0.0/gems/origin-1.1.0/lib/origin/extensions/symbol.rb:67:in `block in evolve`
[PROJECT_ROOT]/vendor/bundle/ruby/2.0.0/gems/origin-1.1.0/lib/origin/extensions/object.rb:193:in `__evolve__`
[PROJECT_ROOT]/vendor/bundle/ruby/2.0.0/gems/origin-1.1.0/lib/origin/extensions/symbol.rb:67:in `evolve`
[PROJECT_ROOT]/vendor/bundle/ruby/2.0.0/gems/mongoid-3.1.4/lib/mongoid/fields/standard.rb:10:in `evolve`
[PROJECT_ROOT]/vendor/bundle/ruby/2.0.0/gems/origin-1.1.0/lib/origin/selector.rb:97:in `evolve`
...
```

**Comment by mnagdewani-systango** [comment]
I am getting same issue in user model even though I don't have any column as a symbol type.All models are working except this.Please help me.
