### ISSUE TITLE
In-place editing?

### ISSUE THREAD

**Issue by nonsense** [railsadminteam/rails_admin#1818]
Hello,

Is it possible to include somehow in-place editing for a given field directly from the list view of a rails_admin model?

I have a model (Photos) and I would like to be able to quickly edit a given field (Caption) for many photos, just by clicking on the field (like a spreadsheet). Going from one individual edit page to another is quite time consuming.

I was wondering if someone has implemented such an action/plugin?

Thanks,
Anton

**Comment by StarWar** [comment]
Can we customize show page to display content how it's supposed to look like to visitors? And use best in place or similar gem to do in place editing?
