### ISSUE TITLE
Paperclip s3 at rails_admin

### ISSUE THREAD

**Issue by Australhawk** [railsadminteam/rails_admin#1838]
When i use paperclip for forms at my app it does upload images to S3, but this doesnt work at the admin panel. Was this ment this way or is a bug?

**Comment by jamescook106** [comment]
Was this issue ever resolved? Currently have this issue

**Comment by 9mm** [comment]
how do we do this... it just uploads locally

**Comment by 9mm** [comment]
The answer is you have to format your initializer properly

```
Paperclip::Attachment.default_options[:storage] = :s3
Paperclip::Attachment.default_options[:s3_credentials] = {
  bucket: Settings.s3.bucket_name,
  access_key_id: Settings.s3.access_key,
  secret_access_key: Settings.s3.secret_key,
  s3_region: Settings.s3.region
}
```
