### ISSUE TITLE
Inconsistent visibility requirement for object_label_method

### ISSUE THREAD

**Issue by nathanl** [railsadminteam/rails_admin#2030]
I'm using version 0.6.2 in an app that includes Country and City models. In the Country show view, its associated cities are listed. Their names are displayed using the `object_label_method` that I have defined.

However, in the City show view, it shows `Details for City ''` - the name is blank.

The issue is that the object_label_method I configured is private, and the two usages within RailsAdmin have differing requirements.
- For the City show view's title, the controller sets @page_name using `wording_for(:title)`, which does `object.try(model_config.object_label_method)` [here](https://github.com/sferik/rails_admin/blob/v0.6.2/app/helpers/rails_admin/application_helper.rb#L48), and `try` returns `nil` unless the method is public.
- However, in the Country show view's list of associated models, it uses the `pretty_value`, which does `associated.send(amc.object_label_method)` [here](https://github.com/sferik/rails_admin/blob/v0.6.2/lib/rails_admin/config/fields/association.rb#L22), and therefore accesses the private method

Why is my method private? Because I'm trying (so far) to keep all RailsAdmin configuration in `config/initializers/rails_admin.rb` and out of the models. So I defined the method in that file, as shown in the [the wiki](https://github.com/sferik/rails_admin/wiki/Railsadmin-DSL):

``` ruby
RailsAdmin.config do |config|
  config.model 'Team' do
    object_label_method do
      :custom_label_method
    end
  end

  def custom_label_method
    "Team #{self.name}"
  end
end
```

Apparently `custom_label_method`, defined this way, is private.

I'm not familiar enough with RailsAdmin to say what the correct change here is: Define this method publicly? Have `wording_for` access the private method via `send`? But it is currently inconsistent.

**Comment by robotfelix** [comment]
I've run into the same problem when using the `rails_admin_import` gem, which also expects the label methods to be public - and the workaround mentioned above to circumvent it.

I guess the main thing is that it should be decided whether or not the `object_label_method` *is* or *isn't* expected to be public, and then documented somewhere.

**Comment by gitjul** [comment]
Still doesn't work 3 years later, needed the workaround with `class_eval` (thanks @nathanl).

**Comment by tomaszgieres** [comment]
And doesn't work even 8 years later. But `class_eval` works @nathanl .

/cc @gitjul ;)

**Comment by mshibuya** [comment]
What's in the Wiki is just wrong, it is supposed to call a model instance method. I've just fixed it.
https://github.com/railsadminteam/rails_admin/wiki/Models#the-object_label_method-method
