### ISSUE TITLE
Possible bug filtering model

### ISSUE THREAD

**Issue by george-good** [railsadminteam/rails_admin#2082]
Version: 0.6.3

**This could well be me not understanding how to configure rails_admin correctly.**

If you create a new model at 00:01 and then filter by Today, that entry won't be shown in the results.

Looking at the log, the SQL that is generated it is subtracting an hour from each end, so the actual range is from 23:00 yesterday to 22:59 today.

```
SELECT  "users".* FROM "users"  WHERE ((users.created_at BETWEEN '2014-10-06 23:00:00.000000' AND '2014-10-07 22:59:59.999999'))  ORDER BY users.id desc LIMIT 20 OFFSET 0
```

_Both should be on the same day_

Dates are stored in the database (postgres) in UTC. The dates display correctly when you view them in rails_admin but you will only see results starting at 01:00.

Looking at the code, I found where the filter is setup, in abstract_model.rb:204 (for the today filter).

Changing the code to

```
def today
  [Time.now.utc, Time.now.utc]
end
```

Fixes the generated SQL and the correct results are returned. I ran the tests and they all still pass.

If it's not a bug, then what am I doing wrong?

**Comment by Sivan1525** [comment]
This seems to be an issue lying for a long time, can we merge the pull / close the issue ?
