### ISSUE TITLE
rails_admin throwing exception at /admin

### ISSUE THREAD

**Issue by rishijain** [railsadminteam/rails_admin#2118]
I think it is of incompatibility between rails_admin and sass-rails. 
Here is the stack I am working on:

Rails (3.2.20)
Ruby (2.0.0p451)
rails_admin (0.4.9)
and thus sass-rails (3.2.6)

Here is the trace:

ActionView::Template::Error (wrong number of arguments (1 for 0)
  (in /Users/rishijain/.rvm/gems/ruby-2.0.0-p451/gems/rails_admin-0.4.9/app/assets/stylesheets/rails_admin/rails_admin.scss.erb)):
    4:     %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
    5:     %meta{:content => "NONE,NOARCHIVE", :name => "robots"}
    6:     = csrf_meta_tag
    7:     = stylesheet_link_tag "rails_admin/rails_admin.css", :media => :all
    8:     = javascript_include_tag "rails_admin/rails_admin.js"
    9:   %body.rails_admin
    10:     #loading.label.label-warning{:style => 'display:none; position:fixed; right:20px; bottom:20px; z-index:100000'}= t('admin.loading')
  sass (3.4.7) lib/sass/script/value/color.rb:597:in `to_s'
  sass (3.4.7) lib/sass/script/value/color.rb:597:in`block in hex_str'
  sass (3.4.7) lib/sass/script/value/color.rb:597:in `map'
  sass (3.4.7) lib/sass/script/value/color.rb:597:in`hex_str'
  sass (3.4.7) lib/sass/script/value/color.rb:565:in `to_s'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:385:in`visit_prop'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:158:in`block in visit'
  sass (3.4.7) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.7) lib/sass/stack.rb:115:in`with_frame'
  sass (3.4.7) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:158:in`visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:420:in `block (2 levels) in visit_rule'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:420:in`map'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:420:in `block in visit_rule'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:179:in`with_environment'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:418:in `visit_rule'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:36:in`visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.7) lib/sass/stack.rb:79:in`block in with_base'
  sass (3.4.7) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.7) lib/sass/stack.rb:79:in`with_base'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:315:in`block (2 levels) in visit_import'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:315:in `map'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:315:in`block in visit_import'
  sass (3.4.7) lib/sass/stack.rb:88:in `block in with_import'
  sass (3.4.7) lib/sass/stack.rb:115:in`with_frame'
  sass (3.4.7) lib/sass/stack.rb:88:in `with_import'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:312:in`visit_import'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:158:in`block in visit'
  sass (3.4.7) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.7) lib/sass/stack.rb:115:in`with_frame'
  sass (3.4.7) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:158:in`visit'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:52:in`map'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:167:in`block in visit_children'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:166:in`visit_children'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:36:in `block in visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:186:in`visit_root'
  sass (3.4.7) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:157:in`visit'
  sass (3.4.7) lib/sass/tree/visitors/perform.rb:8:in `visit'
  sass (3.4.7) lib/sass/tree/root_node.rb:36:in`css_tree'
  sass (3.4.7) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.4.7) lib/sass/engine.rb:268:in`render'
  sass-rails (3.2.6) lib/sass/rails/template_handlers.rb:106:in `evaluate'

**Comment by ilyadoroshin** [comment]
same for me :(

**Comment by ilyadoroshin** [comment]
hello?
