### ISSUE TITLE
Select dropdown filtering has_many through associations not working

### ISSUE THREAD

**Issue by grillermo** [railsadminteam/rails_admin#2130]
In previous versions of Rails Admin(i´m running  0.6.5) the behavior of the select dropdown boxes for belongs_to relationships was to filter as you typed, if there was a list
python
java
pyson
And i typed py, the list would get filtered down to
python
pyson
Now the list stays the same but it makes the py word bold.
With thousands of records this bolden behavior becomes useless, is there any standard way to switch back to the old behavior?

_update_ please read comments

**Comment by franckdelage** [comment]
@grillermo : Thank you very much ! I ran into the same issue and you saved my day !
