### ISSUE TITLE
csv export fails for postgresql database with SQL_ASCII encoding

### ISSUE THREAD

**Issue by birarda** [railsadminteam/rails_admin#2301]
The encoding of the database is not recognized by the csv exporter.

Fails with error: `ArgumentError: unknown encoding name - SQL_ASCII`

This made me discover that our tables really should be utf8 encoded anyways, but seems like a case that should nonetheless be handled for rails_admin csv export.

**Comment by mshibuya** [comment]
Encoding handling changed a lot in https://github.com/railsadminteam/rails_admin/commit/dca8911f240ea11ebb186c33573188aa9e1b031d, please try with the current implementation.
