### ISSUE TITLE
Overriding attribute setter for related models will disable linking to the new model

### ISSUE THREAD

**Issue by mxmzb** [railsadminteam/rails_admin#2584]
I basically implemented this: https://github.com/sferik/rails_admin/wiki/Has-many-:through-association#alternative (the only difference is, that this is for 1:n relations while the code in the wiki is for n:n relations):

``` ruby
  def photo_ids=(ids)
    unless (ids = ids.map(&:to_i).select { |i| i > 0 }) == (current_ids = self.photos.map(&:id))
      (current_ids - ids).each { |id| self.photos.select{ |p| p.id == id }.first.mark_for_destruction }
      ids.each_with_index do |id, index|
        if current_ids.include? (id)
          self.photos.select { |p| p.id == id }.first.position = (index+1)
        else
          p = Photo.find(id).update_attributes({ exercise_id: self.id, position: (index+1) })
        end
      end
    end
  end
```

This though leads to the problem that photos are not being properly linked to the main model, if I am in the process of creating (editing works fine). Obviously, self.id is nil here because self has not been saved yet.
**Yet, Rails Admin will link the photos properly to the newly created model if I don't use this setter** (but then I can't sort things). So I tried to trace it down to your code to make the update just the way you do  (but with the position attribute), but I wasn't able to find it. How did you guys do this?

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
