### ISSUE TITLE
modal for one to many does not pre-populate FK

### ISSUE THREAD

**Issue by pivotal-globehealer** [railsadminteam/rails_admin#2585]
Example: a team has players

Given you edit an existing team,
When you pick "add a team member"
Then the modal should have the team already associated with it

Here's an example from our project. We expected the hospital to be pre-populated when adding an associated image.
![Modal missing hospital FK](https://cloud.githubusercontent.com/assets/17056506/13679172/4aec1ff2-e6a7-11e5-8e07-e8c8d568a373.png)

**Comment by pivotal-globehealer** [comment]
We noticed that the selected_id is blank in the _form_filtering_select.html.haml file.

We believe this to be related to the params[:associations] is also empty. Perhaps this explains why selected_id is blank.

**Comment by RocKhalil** [comment]
+1, any open fix for it ?
