### ISSUE TITLE
Field type not used when filtering on a virtual field

### ISSUE THREAD

**Issue by gabrieletassoni** [railsadminteam/rails_admin#2657]
Hi,
I'm experimenting with using filters directly on virtual fields, I have, in a custom action controller to redirect to chosen_item index, filtered by the object id of an element on a table that has some degree of association with chosen_item:

`redirect_to rails_admin.index_path(:chosen_item,
            {
              f: {
                "#{@object.model_name.singular_route_key}_id_number" => {
                  15769 => {
                    o: :is,
                    v: @object.id
                  }
                }
              },
              #model_name: :chosen_item,
              utf8: "✓"
            }
            )`

The ChosenItem model has a default_scope like this to allow for joins to be setup anyway: 

`default_scope {joins({chosen_furniture: [:furniture, { chosen_room: [:room, {chosen_deck: [:deck, :commission]}]}], furniture_item: :item})}
`

in the rails_admin config I have:

`rails_admin do
  list do
      # I don't want to show this field, just filter on it
      field :commission_id_number, :integer do
        searchable "commissions.id"
        read_only true
        filterable true
        visible false
      end
[...] # some other configs
  end
end`

But it throws me an error, here are the Params sent for the example:

`Parameters: {"f"=>{"commission_id_number"=>{"15769"=>{"o"=>"is", "v"=>"17"}}}, "utf8"=>"✓", "model_name"=>"chosen_item"}`

And the error is:

`ActionView::Template::Error (PG::UndefinedFunction: ERROR:  operator does not exist: integer ~~* unknown
LINE 1: ...furniture_items"."item_id" WHERE ((commissions.id ILIKE '17'...
                                                             ^
`

As you can see, it tries to use ILIKE, instead of =, treating the field (that's a virtual field, with, as you can see, the type overridden by explicitly specifying :integer) as a string and not as an integer.

Is this a bug (field :integer declaration not taken into account by rails_admin when building the query)? Or is there a better way to achieve what I need and this is just me trying to bend the rules? 

Thanks

**Comment by nzajt** [comment]
I know this is old but you can fix this by casting the integer as text like so
```
searchable "commissions.id::text"
```
