### ISSUE TITLE
enhancements - RA total redesign of the GUI

### ISSUE THREAD

**Issue by fmh** [railsadminteam/rails_admin#2698]
- Dashboard more aesthetic
- Right click on the list items
- Main menu accordion style
- Add calendar
- Add PDF printing
- User can select a color theme
- Manage Files & images 
- etc.

I think, i can send a PR in the next 2 months

![capture d ecran 2016-08-22 a 20 59 36](https://cloud.githubusercontent.com/assets/56861/17867970/f46165e2-68ac-11e6-922c-3754191df480.png)
![capture d ecran 2016-08-22 a 21 00 29](https://cloud.githubusercontent.com/assets/56861/17867969/f4610a98-68ac-11e6-81ad-fe1cef0ae2f9.png)
![capture d ecran 2016-08-22 a 21 14 55](https://cloud.githubusercontent.com/assets/56861/17868100/962ca436-68ad-11e6-89d7-15cd228e8052.png)
![capture d ecran 2016-08-22 a 21 12 02](https://cloud.githubusercontent.com/assets/56861/17868250/6058313a-68ae-11e6-89e7-fabf403e0f4b.png)
![capture d ecran 2016-08-22 a 21 16 33](https://cloud.githubusercontent.com/assets/56861/17868128/c4d8d2aa-68ad-11e6-99ec-cf17b58fabcf.png)
![capture d ecran 2016-08-22 a 21 16 03](https://cloud.githubusercontent.com/assets/56861/17868127/c4d76bc2-68ad-11e6-8b7e-33ec6ab47bdd.png)

**Comment by mshibuya** [comment]
Great news, I can't wait to see it working!

One question - does this change completely overrides current appearance? Any plan to provide a way to keep using it?

**Comment by fmh** [comment]
to start, I think use a variable that allows the user to choose which configuration to use. And I'll start with a PR for the dashboard.

**Comment by simonbernard2** [comment]
any news?

**Comment by mshibuya** [comment]
Seems to be stale, please reopen on update.
