### ISSUE TITLE
Is there a way to enable History Page Link (Paper Trail) on side navigation?

### ISSUE THREAD

**Issue by aliahmed922** [railsadminteam/rails_admin#2866]
I did
`config.model "PaperTrail::Version" do
    visible true
  end

  config.model "PaperTrail::VersionAssociation" do
    visible true
  end`
But that doesn't seem to be working.

**Comment by yutoji** [comment]
It's fixed on v2.0.0. See: https://github.com/sferik/rails_admin/commit/87b38b336cc668a74803dec4628215e2e2941248

## Workaround
For your version(probably lower than v2.0.0),
Add this to your `RailsAdmin.config do |config|`:
```ruby
    config.included_models += [PaperTrail::Version, PaperTrail::VersionAssociation]
    # workaround for RailsAdmin lower than v2.0.0
    config.module_eval do
      def self.models_pool
        # excluded = (excluded_models.collect(&:to_s) + %w(RailsAdmin::History PaperTrail::Version PaperTrail::VersionAssociation))
        excluded = (excluded_models.collect(&:to_s) + %w(RailsAdmin::History))

        (viable_models - excluded).uniq.sort
      end
    end
```
