### ISSUE TITLE
add_another and add_edit button not working

### ISSUE THREAD

**Issue by BigmacFR** [railsadminteam/rails_admin#2958]
They redirect to main model list cause by 'data-disable-with' feature.

The button name attribute is not send for disable button.
I add this js to patch the problem (Probably not the best solution)
`$(document).on("click", '.extra_buttons button', function() {
    var input = $("<input type='hidden' />").attr("name", $(this)[0].name).attr("value", $(this)[0].value);
    $(this).closest('form').append(input);
});`
Base on the anwser [commit parameter](https://stackoverflow.com/questions/2000111/rails-is-not-passing-the-commit-button-parameter)
rails_admin 1.2.0 or 1.1.1

**Comment by mshibuya** [comment]
https://github.com/railsadminteam/rails_admin/commit/ac0a563a0bf91bf33c693e19717148ed77f843fd should have solved this.
