### ISSUE TITLE
Wrong most_recent_created

### ISSUE THREAD

**Issue by dexion** [railsadminteam/rails_admin#3010]
now it is 
`@most_recent_created[t.model.name] = t.model.last.try(:created_at)`
rails 5 by default use `order by "model_name".id`. When using `uuid` as `id` it have wrong behaviour. I think this should use sorting order from model's settings
```
rails_admin do
    parent ParentModel
    list do
      sort_by :created_at
    end
end
  ...
```

**Comment by mshibuya** [comment]
This is expected, see #2514.

**Comment by dexion** [comment]
So, I repeat: "it is wrong!". Now it show weather on Mars because rails 5 default sort by uuid. `rails_admin` should have setting for sort order (someone sort by `id` as in #2514, someone should sort by `created_at` or  `updated_at` and have those indexes). If you wish, I can send test cases

**Comment by mshibuya** [comment]
Then letting users to choose which column to use to sort will be the option.
I don't want neither query on unindexed columns or forcing RailsAdmin users to have index, anyway.

**Comment by runephilosof** [comment]
Rails 6 has [implicit_order_column](https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema.html#method-c-implicit_order_column).
Please use that one for ordering.
