### ISSUE TITLE
Last Created not updating correctly

### ISSUE THREAD

**Issue by VinylVault** [railsadminteam/rails_admin#3177]
Hi All,  I have an import script that created a lot of records (12000) in multiple tables over a period of time (multiple hours), but running this script and creating the records, the Last Created field only updates with the first record being created not subsequent ones.  

Is this normal? I don't think it is, so how can I fix it?

**Comment by VinylVault** [comment]
I've also just run this script to add just a few new repeases, and it hasn't update any of the "last updated" fields except the one that is added by the script, can someone please help?
![Opera Snapshot_2019-09-18_194512_192 168 0 11](https://user-images.githubusercontent.com/48488973/65176556-e53f2080-da4c-11e9-91ca-9c1124f5467d.png)

**Comment by mshibuya** [comment]
Newly introduced configuration option can be used for solving this issue.
https://github.com/railsadminteam/rails_admin/commit/d6d380a02e955c3b14ff7dc30f1809a2a6cd0f47#diff-2fb0bbc938298daeb485b167581d31d8a6964d380f6d202f9b6dc83ddcac2914R136
