### ISSUE TITLE
Selected items button doesn't work on production, but work on local

### ISSUE THREAD

**Issue by wolf-hub** [railsadminteam/rails_admin#3202]
For some reason "Selected items" button doesn't work on production (Digital Ocean with Ubuntu 18 + nginx). When i click on this button nothing happens. If i change in inspector display attribute for dropdown which this button should open and click on buttons there, for example "Remove items" button also nothing happens. These clicks also don't throw errors in console. But on my local when i just run rails server command these buttons work nice without any problems

**Comment by mshibuya** [comment]
Sounds like an asset-related issue. Check your configuration.
