### ISSUE TITLE
Support for Webpacker only applications

### ISSUE THREAD

**Issue by Yanchek99** [railsadminteam/rails_admin#3277]
Rails 6 has provided an option to create and run rails applications with assets fully supported by Webpacker.  This allows the application to run without the old rails asset pipeline in Sprockets.  However there seems to be a hard dependency with rails_admin that requires an application to use the asset pipeline.   

When attempting to run the application the following error is presented
```
Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:
```

For a support option ActiveAdmin has solved for this using a config flag. https://github.com/activeadmin/activeadmin/commit/d6f240aa38267806b751f69af322759490de67e1

**Comment by inopinatus** [comment]
Sprockets is dying, and I'm moving all applications over to Webpacker.

If the crushingly long release wait for Sprockets 4 wasn't evidence enough, observe that both autoprefixer-rails and libsass are now deprecated, so any Sprockets-based asset bundle is now technical debt.
