### ISSUE TITLE
(Un)Scope list of embedded Documents

### ISSUE THREAD

**Issue by Nilpointer** [railsadminteam/rails_admin#3285]
Hi, 

I am struggeling with managing a List of embedded Documents which are default-scoped 

class ArchiveField
embedded_in :project
....
default_scope -> { where(visible: true).order_by(position: :asc) }

is embedded in:

class Project
...
embeds_many :archive_fields, class_name: ArchiveField
accepts_nested_attributes_for :archive_fields, allow_destroy: true

In RailsAdmin I would like to see all documents, so I am trying to set
in rails_admin initializer:

config.model ArchiveField do
    list do
      scopes [:unscoped]
    end
  end

But this does not work with the embedded documents - the default_scope is still active when the fields are listed and I only see subdocuments with field visible set to true.

Any suggestions?

Regards
Andi

**Comment by mshibuya** [comment]
https://github.com/railsadminteam/rails_admin/commit/8d905f9e2f1102e8addf324b496720e3fd47bf1d allows you to use unscoped mode.
