### ISSUE TITLE
Use custom action with column_width

### ISSUE THREAD

**Issue by beshur** [railsadminteam/rails_admin#3298]
Hello!

Maybe It's something very basic, but I can't find or understand the syntax.
Is it possible to use custom action in `list` section:
```
field :email_sent do
  label 'Email?'
  column_width 30
  :toggle
end
```

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
