### ISSUE TITLE
Long Messages Truncated in History Tables

### ISSUE THREAD

**Issue by brandon-settle** [railsadminteam/rails_admin#3366]
Hi team! I wish I knew how to fix this myself, but something pretty inconvenient when debugging issues looking at the history of an object is that when the messages are long, the content of the table is visually truncated. Is there a way to enable text-wrapping or horizontal scrolling? Currently, the only way I know to access the hidden content is to inspect the element and view the text within the <td> block.

In the example below, the last row of history has a long message, but its full text isn't shown on the screen. I'd love to be able to scroll horizontally to see it, or even to have text wrapping that made that row larger.

Not sure if this warrants an update to the gem, but I'd at least personally appreciate knowing how I can modify this within my app. Maybe the community at large would appreciate this functionality as well. Thank you!

![image](https://user-images.githubusercontent.com/79821936/122607658-ebf72f00-d048-11eb-8f84-9edbcd5f3b63.png)

**Comment by codealchemy** [comment]
This can be done in CSS

To allow sidescroll

```css
#history tbody tr td {
  overflow: auto;
  text-overflow: inherit;
}
```

To allow text wrapping

```

**Comment by codealchemy** [comment]
Reopening as I didn't mean to close this (but please feel free to close if the solution above work for you!)

**Comment by codealchemy** [comment]
Closing as stale.
