### ISSUE TITLE
Can't save model with associated ActionText with image

### ISSUE THREAD

**Issue by tosbourn** [railsadminteam/rails_admin#3386]
Having followed the guidance to [enable ActIonText within Rails Admin](https://github.com/sferik/rails_admin/wiki/ActionText) I'm still getting an error when saving content that has an image.

Error message: `undefined method 'to_model' for #<ActiveStorage::VariantWithRecord:0x00007f9499bf30d0>`

This is being thrown in my `_blob` partial;

```erb
  <% if blob.representable? %>
    <picture>
      <source srcset="<%= polymorphic_url(blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ], format: :webp), script_name: nil) %>" type="image/webp" />
      <%= image_tag polymorphic_url(blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]), script_name: nil), alt: (blob.caption ? blob.caption : blob.filename), class: "mx-auto rounded-lg", loading: 'lazy' %>
    </picture>
  <% end %>
```

You'll note I've already applied the `polymorphic_url` patch as suggested, in the wiki article.

What I also found odd is if you remove the ActionText content (so the form doesn't have anything to do with ActionText) the error still happens, even though in the payload I can see my content would not have been submitted by the form.

## Notes

related model:

``` ruby
class Article < ApplicationRecord
  include ArticleAdmin
  has_rich_text :content
  ...
end
```

related rails_admin config:

``` ruby
module ArticleAdmin
  extend ActiveSupport::Concern

  included do
    rails_admin do
      list do
        ...
      end

      edit do
        field :approved
        field :title
        field :content
        field :categories
      end
    end
  end
end

```

**Comment by DilankaHerath** [comment]
Did you figure it out? I have the same problem

**Comment by juan-apa** [comment]
I still have this issue, I'm using rails 7. Did you any of you find a solution to this?

**Comment by lrjbrual** [comment]
any update on this? thanks

**Comment by juan-apa** [comment]
for anyone using webpacker (either rails 7 + webpacker, or rails 5, 6 +webpacker), you should follow the guide on setting up actiontext with webpacker [here](https://github.com/railsadminteam/rails_admin/wiki/ActionText#full-featured-setup-using-webpacker).
I'm still stuck trying to figure out how to set it up with rails 7 + importmap though.

**Comment by rbngzlv** [comment]
Hi! I'm not using `rails_admin` but I hitted the same error with another gem to build admin interfaces. After digging into it, the reason seems to be that we are rendering the partial from an isolated engine (https://github.com/rails/rails/issues/31325) and it doesn't know how to resolve the polymorphic url.

The easiest solution that worked for me is to edit the partial `app/views/active_storage/blobs/_blob.html.erb` to use `main_app.url_for` to pass directly pass the url to the `image_tag` helper: 

```diff
- <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
+ <%= image_tag main_app.url_for(blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])) %>
```

It should also work using `main_app.polymorphic_url` instead of only `polymorphic_url`, so if someone using this project can validate the solution, perhaps the wiki article (mentioned in the opener post) can be updated.

**Comment by Tronerta** [comment]
> for anyone using webpacker (either rails 7 + webpacker, or rails 5, 6 +webpacker), you should follow the guide on setting up actiontext with webpacker [here](https://github.com/railsadminteam/rails_admin/wiki/ActionText#full-featured-setup-using-webpacker). I'm still stuck trying to figure out how to set it up with rails 7 + importmap though.

Hi, any progress with rails 7 + importmap?
