### ISSUE TITLE
Introduce importmap-rails for JavaScript dependency management

### ISSUE THREAD

**Issue by mshibuya** [railsadminteam/rails_admin#3399]
It will be the default way from Rails 7.
https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b

**Comment by brunoprietog** [comment]
Hello, is there any news about this? I am using Rails 7 and propshaft instead of sprockets as my asset pipeline and I get an error on installation because sprockets is required.

Thanks!

**Comment by mshibuya** [comment]
I realized that this is possible now, after upgrading Bootstrap to 5 we now have no ESM-incompatible dependencies.
I'll try to see if it works or not soon.

**Comment by jessenovotny** [comment]
Is there a corrected rails_admin:install command to work with importmap?
