### ISSUE TITLE
how to show part data in a multi select on has_and_belongs_to_many relation 

### ISSUE THREAD

**Issue by demo360o2** [railsadminteam/rails_admin#3405]
I have a class with a has_and_belongs_to_many that is shown in a multi select

has_and_belongs_to_many :categories

when displayed in a form the left side of the multi-select is filled with all the categories.

Is there a way to only have part of those categories. I what to filter some out based on a propertie of the object

![categories](https://user-images.githubusercontent.com/60194027/137513567-e9caab91-46b9-416f-9d19-d7ac941d5d24.png)

**Comment by mshibuya** [comment]
You need `associated_collection_cache_all false` as well.
https://github.com/sferik/rails_admin/wiki/Associations-scoping

**Comment by demo360o2** [comment]
with this
            associated_collection_cache_all false
            associated_collection_scope do
              Proc.new { |scope|
                scope = scope.where(school_type_id: 5)
                puts "@@@####@@@@####"
                puts scope.inspect
                scope
              }
            end

I got a to many object in the left pan and I can't see my debug trace in the out put...

Any clue?
