### ISSUE TITLE
Is there the function to call like a mail template on edit?

### ISSUE THREAD

**Issue by HeppokoNeet** [railsadminteam/rails_admin#3446]
It's just a question.
Is it possible to set a text template on edit for Rails-Admin?

Whenever inputting some data, it takes a long time.
So, I think if I can call like a mail template, it would takes a short.

I searched that kind of the function for Rails-Admin but I couldn't find it..
Any ideas?

**Comment by codealchemy** [comment]
You can overrride [the template](https://github.com/railsadminteam/rails_admin/blob/master/app/views/rails_admin/main/edit.html.erb) (and / or related helper functions) within your project. An example of doing this for the `show` action can be found [in the Wiki](https://github.com/railsadminteam/rails_admin/wiki/Show-view-styling).

If this doesn't solve your issue, please [refer to the mailing list](https://github.com/railsadminteam/rails_admin/blob/master/CONTRIBUTING.md#getting-help) for additional help.
