### ISSUE TITLE
rails_admin unsupport rails 7.0

### ISSUE THREAD

**Issue by bill1997603** [railsadminteam/rails_admin#3447]
I want to use rails 7.0, but perform bundle command error 

Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 7.0.0)

  In Gemfile:
    rails (~> 7.0.0)

    rails_admin (~> 2.0) was resolved to 2.2.1, which depends on
      rails (< 7, >= 5.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by mshibuya** [comment]
Use the master branch, or wait for the next release.
