### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by guillaumebriday** [railsadminteam/rails_admin#3449]
Hey 👋 

Rails 7 is out 🎉  I see commits about some testing on Rails 7 RC. Is it working fine? If so, could you release a new version please? Or how can we help?

Thanks 👍

**Comment by ciscolive** [comment]
+1

**Comment by mshibuya** [comment]
RailsAdmin 3.0.0.beta was released. Trying it out and giving feedback will make the 3.0.0 release faster.

```ruby
gem 'rails_admin', '3.0.0.beta'
```

Also please check this if you're upgrading from 2.x.
https://github.com/railsadminteam/rails_admin#upgrading-from-2x

**Comment by tachyons** [comment]
@mshibuya Does that means 2.x won't have support for rails 7, I am bit reluctant to upgrade to 3.x as it requires webpacker dependency and we already moved from webpacker to jsbundle-rails

**Comment by mshibuya** [comment]
> it requires webpacker dependency

No way. `jsbundling-rails` comes with webpack (not webpacker), and RailsAdmin also supports that setup.

**Comment by yubele** [comment]
@mshibuya 
>No way. jsbundling-rails comes with webpack (not webpacker), and RailsAdmin also supports that setup.
Are there any plans to support esbuild via propshaft?

**Comment by thubamamba** [comment]
Upgrading breaks everything. Any ideas how to rectify this? 
<img width="1440" alt="CleanShot 2022-03-01 at 07 20 48@2x" src="https://user-images.githubusercontent.com/22769109/156109902-807caeb6-7d2d-498b-921a-8a5dafe79593.png">

**Comment by mshibuya** [comment]
@yubele 

> jsbundling-rails comes with webpack (not webpacker), and RailsAdmin also supports that setup.

About this part, I realized that I need some more work. #3488 is the ongoing attempt for that, it would be great if you could test it and provide feedback.

@thubamamba
Do you use Webpacker, or just Webpack via jsbundling-rails?

**Comment by mshibuya** [comment]
Closing, since #3488 was merged in.
