### ISSUE TITLE
rails 7.0.0

### ISSUE THREAD

**Issue by UmPlat** [railsadminteam/rails_admin#3451]
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 7.0.0)

    rails_admin was resolved to 2.2.1, which depends on
      rails (>= 5.0, < 7)

**Comment by ciscolive** [comment]
+1

**Comment by mshibuya** [comment]
Duplicate pf #3449.
Please stop opening a new issue, without checking if there's the same one. It's just a waste of time.
