### ISSUE TITLE
rails_admin.css cannot be found by webpacker after compilation on rails_admin 3.0.0.beta

### ISSUE THREAD

**Issue by estebanz01** [railsadminteam/rails_admin#3453]
**Describe the bug**
👋 Hello again!

Testing `3.0.0.beta` with a staging environment, I came up with this error:

```ruby
[1f8b3ad2-ef8c-4856-a55b-5d997308e8f0] ActionView::Template::Error (Webpacker can't find rails_admin.css in /home/ubuntu/app/public/js/packs/manifest.json. Possible causes:                   
1. You want to set webpacker.yml value of compile to true for your environment                                                                                                                             
   unless you are using the `webpack -w` or the webpack-dev-server.                                                                                                                                        
2. webpack has not yet re-run to reflect updates.                                                                                                                                                          
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
```

In order to fix it, I had to include `app/javascript/stylesheets` into `config/webpacker.yml` in the `additional_paths:` section. Not sure if it's a configuration issue or something we need to tell rails to pick up, so feel free to ignore this if that's the case.

```json
additional_paths: ['app/javascript/stylesheets'] // config/webpacker.yml
```

**Reproduction steps**
1. Compile webpacker assets for staging or production environment.
2. Run the application in staging or production environment.

**Expected behavior**
I expect rails to compile the `rails_admin.css` file when compiling webpacker assets.

**Additional context**

- `rails` version: 6.0.4.4.
- `rails_admin` version: 3.0.0.beta

**Comment by mshibuya** [comment]
I couldn't reproduce this locally in a normal way. The only step was:

- Build assets by `rails assets:precompile` in development mode (= `extract_css: false`)
- Serve assets in production mode (= `extract_css: true`)

So I suspect this to be inconsistency of extract_css. Also `additional_paths` didn't make any difference.

Could you check the process you build assets?

**Comment by estebanz01** [comment]
I'll try to test again from a clean rails app to see what happens.

**Comment by estebanz01** [comment]
OK, I tested this again in a fresh rails app and it compiles with `production` environment. It seems it's a problem with my configuration in a different environment (`staging`). I'd consider this an user problem, so I'm going to close it.
