### ISSUE TITLE
Disable shrine

### ISSUE THREAD

**Issue by oskarcompany** [railsadminteam/rails_admin#3459]
How do you disable shrine support?!

**Comment by mshibuya** [comment]
It won't be enabled unless you explicitly do so.

**Comment by oskarcompany** [comment]
yes but if you have it enabled but you dont want rails_admin to automatically handle shrine?

**Comment by mshibuya** [comment]
Sorry this is the issue tracker, please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request.
