### ISSUE TITLE
Add a button to the standard view

### ISSUE THREAD

**Issue by sas2job** [railsadminteam/rails_admin#3476]
How can I add a button to the standard view of the model?
Use rails_admin 2.1.1/ruby 2.6.6

**Comment by codealchemy** [comment]
This depends on what you'd like the button to do (a custom action, simple link, something else). Some of this is covered in [the Wiki](https://github.com/railsadminteam/rails_admin/wiki/Fields#output-formatting), and there's [the mailing list](http://groups.google.com/group/rails_admin) for support requests if you're unable to find anything in the Wiki for what you're looking to do.
