### ISSUE TITLE
Sorting by clicking table header doesn't work anymore

### ISSUE THREAD

**Issue by DanAndreasson** [railsadminteam/rails_admin#3497]
**Describe the bug**
Nothing happens when clicking on a table header. Previously it sorted (and then reverse sorted) if you clicked it. Everything else works as expected for us.

**Reproduction steps**
Steps to reproduce the issue seen.

**Expected behavior**
In previous versions, you are able to click on a table header (in the index view) to sort by that column.

**Additional context**

- `rails` version: 7.0.2.2
- `rails_admin` version: 3.0.0.rc4
- full stack trace (if there's an exception)

**Comment by mshibuya** [comment]
Sorry for the issue, fixed in the `3.0-stable` branch so please give it a try.

```ruby
gem 'rails_admin', github: 'railsadminteam/rails_admin', branch: '3.0-stable'
```
