### ISSUE TITLE
No more loading indicator on version 3

### ISSUE THREAD

**Issue by jeromedalbert** [railsadminteam/rails_admin#3500]
**Describe the bug**

When clicking on items in the left navbar, there is no loading indicator any more. There used to be one in the older rails_admin version.

This is especially problematic when loading lists that take many seconds to load. Since there is no indicator, the user is not sure whether the page is loading or if they misclicked. So they might click again (and again, and again), but if they correctly clicked the first time, this may lead to cascading delays.

**Reproduction steps**

Click on any item in the left navbar that takes a little bit of time to load.

**Expected behavior**

A loading indicator should be shown. Here is a screenshot of the indicator from the older rails_admin version, showing at the bottom-right of the page:

<img width="192" alt="Screen Shot 2022-03-24 at 7 14 08 PM" src="https://user-images.githubusercontent.com/236461/160041640-324ab085-8c4a-416e-ae38-8f8147c773db.png">

**Additional context**

- `rails` version: 7.0.2.3
- `rails_admin` version: 3.0.0

I am using `config.asset_source = :sprockets` in `config/initializers/rails_admin.rb`, but I also tried with `config.asset_source = :webpacker` to no avail.

Maybe the problem started to happen during the switch to Turbo.

**Comment by mshibuya** [comment]
Yeah we removed it when we stopped using Pjax.
I can be added back, but how important is it? I initially thought that it won't make noticeable differences...

**Comment by jeromedalbert** [comment]
I think it is somewhat useful to display `list` pages that take a long time to load because they are many columns.

Alternatively a loading indicator may not be that needed if `list` pages could be made to load faster by default, for example by displaying only the X first columns. As a workaround I have sped up my list pages by manually whitelisting attributes with `list do ... end` for my 50 models (which was a bit time consuming!).

**Comment by jeromedalbert** [comment]
Thanks for tackling this @mshibuya. After trying the latest `master` both with the asset pipeline or with webpacker, I don't see the loading indicator.

I managed to sort of make it work by hacking `app/javascript/packs/rails_admin.js` like so:

```javascript
import "rails_admin/src/rails_admin/base";
import "../stylesheets/rails_admin.scss";

$(document).on("turbo:click", function () {
  return $("#loading").show();
});
```

Although I shouldn't have to do it since `src/rails_admin/ui.js` should take care of it. Also, when I click to go back one page in my browser, the loading indicator still shows. I am wondering if something is wrong with my setup.

**Comment by mshibuya** [comment]
> when I click to go back one page in my browser, the loading indicator still shows.

Added the fix for this behavior in https://github.com/railsadminteam/rails_admin/commit/b9ee7f0c202abc7c09726bdaa28536e7ec25127e, thanks!
