### ISSUE TITLE
RailsAdmin 3.0 design is confusing after upgrade

### ISSUE THREAD

**Issue by MichaelHoste** [railsadminteam/rails_admin#3507]
**Describe the bug**

After updating to RailsAdmin 3.0, I was so confused by the new very contrasted design that I was convinced that something was wrong with my assets because of the Webpacker migration. I spent some time trying to fix it.

I had to install the dummy app with 2.x and 3.0 to understand that this design was in fact expected behaviour.

**RailsAdmin 2**

![Screenshot 2022-04-08 at 11 43 44](https://user-images.githubusercontent.com/529357/162411999-85214c14-0cc2-4d5c-8444-3230437c2c7d.png)

**RailsAdmin 3**

![Screenshot 2022-04-08 at 11 44 14](https://user-images.githubusercontent.com/529357/162412008-c24c03f4-c16e-442a-b5c8-9f0c884f94b8.png)

Maybe that's something that should be slightly improved out-of-the-box? (no more flashy blue?)

Another solution would be to add a screenshot somewhere so that people knows what to expect after an upgrade.

I know that "nice design" is very relative but if you are interested, I may try to add a few CSS styles so that the 3.x version looks more like the 2.x version (smoother colors and improved padding).

Please let me know.

**Reproduction steps**

Fresh install of RailsAdmin 2 and RailsAdmin 3

**Expected behavior**

A relatively close design.

**Additional context**

Thanks a lot for this great project! 😉

**Comment by codealchemy** [comment]
This can be done by adding a `variables.css.scss` and adding 

```scss
// Keep info and primary colors the same as Bootstrap 3
$primary: #428bca;
$info: #5bc0de;

// Force light color for top-nav links
$navbar-dark-color: white;

// Contrast ratio used to calculate color for text within elements (ie. buttons)
// https://getbootstrap.com/docs/5.0/customize/sass/#color-contrast
$min-contrast-ratio: 2;
```

(not perfect, but close - I'll update the [theming docs](https://github.com/railsadminteam/rails_admin/wiki/Theming-and-customization) as well to provide some better direction)

**Comment by mshibuya** [comment]
Just added another configuration point in https://github.com/railsadminteam/rails_admin/commit/126f7ac79b2ce7846cbbed7bbca1cc26dfe46fb6. By using this achieving the similar appearance will be easier.
