### ISSUE TITLE
Empty file field deletes previously attached files when updating a record that has active_storage

### ISSUE THREAD

**Issue by Shpigford** [railsadminteam/rails_admin#3520]
I have a vanilla `Art` model with `has_many_attached` in it...

```ruby
class Art < ApplicationRecord
  has_many_attached :images
  belongs_to :art_category
end
```

This appropriately adds an "Images" field in rails_admin, and when creating a new record, it works perfectly.

![CleanShot 2022-05-19 at 16 04 24@2x](https://user-images.githubusercontent.com/35243/169404399-c4380f3c-3a5a-4541-93cf-2be3da40c248.png)

However, if I return to that record and update any other field (but don't touch the images), it deletes the associated image.

```
Parameters: {
  "authenticity_token"=>"[FILTERED]", 
  "art"=>{
    "name"=>"mountains", 
    "description"=>"this is a description i'm writing", 
    "tools"=>"midjourney, photoshop, wombo", 
    "nft"=>"1", 
    "external_link"=>"https://opensea.io/...", 
    "art_category_id"=>"1", 
    "images"=>[""]
  }, 
  "return_to"=>"http://localhost:3000/admin/art_category/new", 
  "_add_edit"=>"true", 
  "model_name"=>"art", 
  "id"=>"6"
}
```

As you can see, the `images` field is submitting a blank array.

Is this a setting I'm missing? Or is this a bug?

**Additional context**

- `rails` version: 7.0.3
- `rails_admin` version: 3.0.0

**Comment by darrenterhune** [comment]
I'm on latest stable rails 6.0 and rails_admin 3.0.0 and don't have this issue. We do however follow this https://github.com/railsadminteam/rails_admin/wiki/ActiveStorage#deleting-an-attachment but that shouldn't affect what you're seeing afaict

**Comment by mshibuya** [comment]
Thanks for reporting. This is because of those changes in ActiveStorage.
https://github.com/rails/rails/commit/4f191b975431dbf8071d73a48505e27b19c283e6
https://github.com/rails/rails/commit/400b2103540e1dfb370eab29a891687d778ad357
Pushed the fix into the master branch, so please try it when you get a chance.

**Comment by aliceclv** [comment]
I'm still experiencing that issue.
Pictures and videos attached are sent as an empty array.
Here are the parameters sent on update, the issue is only happening on production though. I'm using rails 7.1.1 and rails_admin: 3.1.2
```
2023-11-07T18:31:22.238168+00:00 app[web.1]: I, [2023-11-07T18:31:22.238151 #2]  INFO -- : [7f779e8f-5686-4cbc-8cec-7d3add8a9b94]   Parameters: {"authenticity_token"=>"[FILTERED]", "seller_item"=>{"seller_id"=>"xxx", "featured"=>"1", "title"=>"", "description"=>"", "pictures"=>[""], "videos"=>[""]}, "return_to"=>"xxxxx", "_save"=>"", "model_name"=>"seller_item", "id"=>"xxxx"}
```
