### ISSUE TITLE
Association display changed after migrating to rails_admin 3.0

### ISSUE THREAD

**Issue by bricedurand** [railsadminteam/rails_admin#3521]
Hello,

I've migrated my application from rails_admin 2.2 to 3.0 and it is usable, however some views have changed without changing the model code.

I have a Student model which belongs to a School :
```ruby
class Student < User
    belongs_to :school, optional: true

    rails_admin do
      list do
        field :school
      end

      edit do
        field :school
     end
  end
end
```
Here are the changes :
**List view**
In my 2.2 list view, the school was displayed as a link, which was a nice way to navigate in the admin.
![2022-05-23 link to school in user list view rails_admin 2](https://user-images.githubusercontent.com/1522772/169798653-d3d01408-fb4f-4d3d-b055-a1bc9c493fab.png)
Now in 3.0 list view, I lost the link :
![2022-05-23 link to school in user list view rails_admin 3](https://user-images.githubusercontent.com/1522772/169798713-9694ede8-8bfc-4ba5-aa27-cf0190d78323.png)

**Show view**
In 2.2 show view, I also had a link
![2022-05-23 link to school in user show view rails_admin 2](https://user-images.githubusercontent.com/1522772/169799065-1699cbc9-c354-496a-a113-42e4ad22bac4.png)

And now in 3.0 show view it is just the ID :
![2022-05-23 link to school in user show view rails_admin 3](https://user-images.githubusercontent.com/1522772/169799104-1452217f-3cc4-4419-abc3-c689649cc399.png)

**Edit view**
In 2.2 edit view, there was a select box to change the school, plus a button to modify the school or add a new one.
![2022-05-23 link to school in user edit view rails_admin 2](https://user-images.githubusercontent.com/1522772/169799534-77b30633-aac8-43ae-8cc7-f856328c0652.png)

In 3.0 edit view there is only an input with the name of the school
![2022-05-23 link to school in user edit view rails_admin 3](https://user-images.githubusercontent.com/1522772/169799702-fb7c82aa-3884-4adc-9fcb-2c1a03e62eb1.png)

Is it possible to get the old display back? I haven't found anything regarding field configuration that would give me the old behaviour.

**Comment by mshibuya** [comment]
What's the exact version of RailsAdmin?
Could you try these in Rails console and provide output?

```ruby
RailsAdmin::Config.model(School).fields.find {|f| f.name == :school }
RailsAdmin::Config.model(School).show.fields.find {|f| f.name == :school }
```

**Comment by bricedurand** [comment]
Hello, thanks for taking the time to answer this.

The exact version of RailsAdmin is 3.0.0.

Here is the first output : 
```
RailsAdmin::Config.model(School).fields.find {|f| f.name == :school }

Traceback (most recent call last):
/Users/brice/.rvm/gems/ruby-2.7.2@monstage/gems/rails_admin-3.0.0/lib/rails_admin/config/fields.rb:50:in `factory': undefined method `properties' for nil:NilClass (NoMethodError)
```

The second command has the same output : 
```
 RailsAdmin::Config.model(School).show.fields.find {|f| f.name == :s
chool }

Traceback (most recent call last):
/Users/brice/.rvm/gems/ruby-2.7.2@monstage/gems/rails_admin-3.0.0/lib/rails_admin/config/fields.rb:50:in `factory': undefined method `properties' for nil:NilClass (NoMethodError)
```

**Comment by mshibuya** [comment]
Sorry it was my mistake, there ones:

```ruby
RailsAdmin::Config.model(Student).fields.find {|f| f.name == :school }
RailsAdmin::Config.model(Student).show.fields.find {|f| f.name == :school }
```

I want to know how RailsAdmin detects that `school` field.

**Comment by bricedurand** [comment]
Ok, the Student model is in a module 'Users' so I ran it like this :
```ruby
RailsAdmin::Config.model(Users::Student).fields.find {|f| f.name ==
 :school }

RailsAdmin::Config.model(Users::Student).show.fields.find {|f| f.na
me == :school }
```

Both return nil. There are other fields but not school.

I also ran this on model School 
```ruby
RailsAdmin::Config.model(School).fields
```
and had the same error as above

**Comment by mshibuya** [comment]
Thanks. To investigate the issue I need to be able to reproduce it.
Could you try creating a new Rails application and generating relevant models to reproduce? If you can upload it to a public repo or gist it will be super-helpful.

**Comment by bricedurand** [comment]
I will try with a new app but I doubt that it is the best approach, because the issue appeared from migration existing a code base from RailsAdmin 2.2.1 to 3.0.0. So I'd rather emove code step by step and see when it is working again.

I'm actually working on a public repo : https://github.com/betagouv/monstage
You can try running it but you might run into issues like broken db migrations. At least you have access to the whole source code.

I'll take some time to try to reproduce this issue and help you with the project setup if you want to investigate.

**Comment by mshibuya** [comment]
Your app was too big to be fully run, but I partially tested it and found out that with the RailsAdmin master branch the school field was correctly detected.

```
> RailsAdmin.config(Users::Student).fields.find{|f| f.name == :school}
=> #<RailsAdmin::Config::Fields::Types::BelongsToAssociation[school] ...>
```

Could you also try that?

```
gem 'rails_admin', '~> 3.0', github: 'railsadminteam/rails_admin'
```

**Comment by bricedurand** [comment]
I tried using master branch and it worked !

I also realized this issue was only happening on my local machine, and not on production. Haven't found the reason why though...

**Comment by mshibuya** [comment]
My guess is it's something related to the initialization process. I won't go further for now, since #3541 seems to work.
Thank you for reporting.
