### ISSUE TITLE
Adding to has_many associations is broken in 3.x

### ISSUE THREAD

**Issue by NuckChorris** [railsadminteam/rails_admin#3526]
**Describe the bug**
I updated our app (https://github.com/hummingbird-me/kitsu-server) to Rails Admin 3.0 and we're now seeing an issue with adding items to has_many associations where the created item is never added to the association form, and if you save the page, it deletes the association (presumably since Rails gets an empty array for the association)

**Reproduction steps**
1. Open edit page
2. Add item to association
3. In modal, create the item
4. Press "save" in modal
5. The JSON response appears in the modal but is not added to the form. Clicking save again after this scrolls you to the top of the page and throws an error to the console
6. Press save on entire page
7. Association item is deleted

https://user-images.githubusercontent.com/430411/172036135-2277a338-040a-43ba-8ef3-39d2909e106b.mov

**Expected behavior**
Rails Admin should add the newly-created item to the list

**Additional context**

- `rails` version: 6.1.6
- `rails_admin` version: 3.0.0
- `rails_admin` npm package version: N/A
- full stack trace (if there's an exception)

(when clicking save a second time, probably because the form it's targeting is now undefined, since it's been replaced by JSON)
```
Uncaught TypeError: Cannot read properties of undefined (reading 'dispatchEvent')
    at Object.Rails.fire (application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:155:13)
    at HTMLAnchorElement.<anonymous> (application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:41510:17)
    at HTMLAnchorElement.dispatch (application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:10199:27)
    at HTMLAnchorElement.elemData.handle (application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:10003:28)
Rails.fire @ application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:155
(anonymous) @ application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:41510
dispatch @ application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:10199
elemData.handle @ application-255c2d40aaecfb69d2a41cf103d8bfb216bfc7d88c16b45b68a26afceec4e36a.js:10003
```

Since we're all open-source, here's our Rails Admin config:

https://github.com/hummingbird-me/kitsu-server/blob/the-future/config/initializers/rails_admin.rb

The Mapping model (the type in the modal):

https://github.com/hummingbird-me/kitsu-server/blob/the-future/app/models/mapping.rb

The association itself:

https://github.com/hummingbird-me/kitsu-server/blob/the-future/app/models/concerns/mappable.rb#L5

**Comment by mshibuya** [comment]
Maybe related to #3515. It's already in the master branch so could you try it?

**Comment by NuckChorris** [comment]
Master branch is working, thanks! Is it possible to prefill the association inverse field in the modal? I feel like that used to work 🤔

**Comment by NuckChorris** [comment]
Figured out a solution, thanks!
