### ISSUE TITLE
Live demo doesn't work

### ISSUE THREAD

**Issue by babilonczyk** [railsadminteam/rails_admin#3537]
Live demo doesn't work. It should be fixed.

**Comment by mshibuya** [comment]
Yeah I was aware that it's been like this for a long time...

> [automate a Heroku deployment](https://github.com/marketplace/actions/deploy-to-heroku) based on the dummy_app

I love to try this.

**Comment by faqndo97** [comment]
@mshibuya Do you need any help to put demo live again? I can help to fix whatever it is and deploy it again to heroku or other provider.

**Comment by codealchemy** [comment]
Looks like Heroku is no longer the best provider to host (they've been [phasing out free plans](https://twitter.com/heroku/status/1562817050565054469?cxt=HHwWisDUvfn0nrArAAAA) used by other OSS projects, https://relishapp.com/ has been down this week), https://railway.app/ seems like a viable alternative (there's a $5 monthly credit - not sure how quickly this project would burn through that).

**Comment by codealchemy** [comment]
True - the [developer plan](https://docs.railway.app/reference/plans#developer-plan-offering) could still work (not free, but not very costly either - and at that point Heroku may still be preferred). It'd be great if there was an alternative that could host the demo for free, not sure if there are any left out there and open to suggestions.

**Comment by dcecile** [comment]
Fly.io has a free plan, and they've seen a lot of people migrate from Heroku: https://fly.io/docs/rails/

**Comment by mshibuya** [comment]
Finally, it's up on Fly.io 🎉 
https://rails-admin.fly.dev/admin/
