### ISSUE TITLE
Sidebar inconsistencies with collapse behavior

### ISSUE THREAD

**Issue by codealchemy** [railsadminteam/rails_admin#3553]
**Describe the bug**

Side navigation with multiple groups (such as static links in addition to configured models) can move around depending on the state of a given dropdown within the side navigation. 

<details>
<summary>Example using the dummy app from /spec</summary>

![collapse-nav-default](https://user-images.githubusercontent.com/4504083/193148921-c8412bda-f16c-4ee9-a0de-f4732cd41625.gif)

</details>

**Reproduction steps**

Start demo app, visit the dashboard. 

**Expected behavior**

Side navigation width and group stacking to be static / consistent.

**Additional context**

- `rails` version: `7.0.x`
- `rails_admin` version: `master` branch
- `rails_admin` npm package version: `master` branch
- full stack trace (if there's an exception) N/A

Collapsable sidebar introduced in https://github.com/railsadminteam/rails_admin/commit/e8cb8edd39246bf75ed72295b7832faf5056367c

**Comment by mshibuya** [comment]
Sorry about this, it was broken by ef76fcea0b23aed04f6568448cd157ccc9ba30a0 and fixed in the master now.

**Comment by codealchemy** [comment]
Looks good, thanks!
