### ISSUE TITLE
rails_admin 3.1.0 causes error when referencing Ability class in initializer as described in wiki

### ISSUE THREAD

**Issue by okuramasafumi** [railsadminteam/rails_admin#3563]
**Describe the bug**

https://github.com/railsadminteam/rails_admin/wiki/CanCanCan#use-different-ability-classes-for-front-end-and-admin

Loading an ability class located in `app/models/abilities` directory, it causes an error.

**Reproduction steps**

When I follow the description of this wiki page and configure RailsAdmin like below:

```ruby
# MyAbility class is located in app/models/abilities/my_ability.rb
config.authorize_with :cancancan, Abilities::MyAbility
```

the following error occurs:

```ruby
The constant Abilities is not loaded yet upon the execution of the RailsAdmin initializer.
We don't recommend to do this and may lead to issues, but if you really have to do so you can explicitly require it by adding:

  require 'abilities'

on top of config/initializers/rails_admin.rb.
```

**Expected behavior**

We should be able to specify the custom ability class located in `abilities` directory.

**Suggestion**

I'd like to suggest the following way:

```ruby
config.authorize_with :cancancan, 'Abilities::MyAbility'
```

so that we can later classify the given string.

**Additional context**

- `rails` version: Rails 6.1.6.1
- `rails_admin` version: 3.1.0 
- `rails_admin` npm package version: None
- full stack trace (if there's an exception)

**Comment by codealchemy** [comment]
Documentation updated (the change in RailsAdmin happened in https://github.com/railsadminteam/rails_admin/commit/f84ca1c7abc9c6685802ddb62f52ffc6e5008e55), thanks for the report!
