### ISSUE TITLE
Sidebar Menu not wrapping horizontally after changes for Bootstrap 5.2

### ISSUE THREAD

**Issue by jklimke** [railsadminteam/rails_admin#3564]
**Describe the bug**

Since the commit https://github.com/railsadminteam/rails_admin/commit/d7abba4e8a2e380b4d7f8fb3b37302300af63de5 the sidebar of rails_admin within my app is broken as it does not add scrolling but the ul list extends horizontally when all the models are extended (i.e., on load of the rails admin dashboard page). 

This Image shows the effect.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1150217/201875296-97b7581c-d713-4032-8576-9ba22c0001c8.png">

when i remove the "flex-colum" class that was added in the mentioned commit all looks fine again.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/1150217/201875638-79b15bf7-51e2-44ea-9463-3e418fe66d3f.png">

**Reproduction steps**

**Expected behavior**

Sidebar show add vertical scrolling 

**Additional context**

- `rails` version: 6.1.7
- `rails_admin` version: 3.1.2
- `rails_admin` npm package version: 3.1.2

I use webpacker to bundle assets and stylesheets. i checked that bootstrap 5.2.2 was used in the rails admin bundle.  The rest of my app is still using bootstrap 4.6 but that is not included in the rails_admin pack. 

Any hints why this happens ?

**Comment by mshibuya** [comment]
That's my bad, fixed in the master branch 🙇
