### ISSUE TITLE
Papertrail Versions stopped being displayed in Rails 7

### ISSUE THREAD

**Issue by alexs333** [railsadminteam/rails_admin#3604]
**Describe the bug**
In all version of Rails prior to 7, I was able to add `PaperTrail::Version` model to the list of models managed by rails_admin:

```
  # config/initializers/rails_admin.rb

  config.model 'PaperTrail::Version' do
    label 'Vehicle history'
    list do
      limited_pagination true
    end
  end
```

**Reproduction steps**
Simply by loading rails admin, the option appears in the list of models in rails prior to version 7, and disappears after upgrade to rails 7.

**Expected behavior**
Expected the 'Vehicle History' in the list of models.

**Additional context**

- `rails` version: 7
- `rails_admin` version: 3.1.1 (also tried with 3.0)
- `rails_admin` npm package version: 3.1.1

**Comment by mshibuya** [comment]
This should be a bug, since not showing a configured model without any notice doesn't make sense. I couldn't figure out where this behavior change came from though...

Now fixed in the master. Thank you for reporting!
