### ISSUE TITLE
i18n Japanese date format cannot be filtered 

### ISSUE THREAD

**Issue by CHEN-WEI-YU** [railsadminteam/rails_admin#3625]
**Describe the bug**
It seems that i18n use the long format, which is "%Y年%m月%d日(%a)", to show in the table list. When filtering, it deliver by this format and cannot search from database

```
  config.model "model_name" do
    configure :date_field_name do
      strftime_format "%Y-%m-%d"
    end
  end
```
I do this to let filter work, but it will display the column in this format too.

**Reproduction steps**
Use datepicker to pick a date on date field to filter, but not working.

**Expected behavior**
Show the list date field column in i18n long format, but deliver by iso8601 when filtering will be better.

**Comment by mshibuya** [comment]
It is not supposed to perform like this after https://github.com/railsadminteam/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a. So my guess is that you have old RailsAdmin assets somewhere in your app, via vendorizatiion or something.
Please check it, and if the issue still happens please let me know.
