### ISSUE TITLE
Rails Admin not functioning with nginx

### ISSUE THREAD

**Issue by Shivyoddha** [railsadminteam/rails_admin#3634]
**Describe the bug**
Rails admin gem works perfectly fine with localhost but when we put it to our server using nginx then it gives doesn't take any new input for tables and doesnt allow editing also. Also we cannot export the data, when we try doing so it gives internal server error.

**Reproduction steps**
Host a rails application through nginx as your server and check for rails admin functionalities

**Expected behavior**
It should work as fine as it was with localhost.

**Additional context**

- `rails` version: 6.1.7.2
- `rails_admin` version: 3.0
- `rails_admin` npm package version:
- full stack trace (if there's an exception)

**Comment by mshibuya** [comment]
Basically what this means is you're not setting up Nginx or other related components correctly. If you think that RailsAdmin is to be blame, you should give a reasonable explanation on why that's not the case.
