### ISSUE TITLE
Pagination not working on scopes

### ISSUE THREAD

**Issue by Etx17** [railsadminteam/rails_admin#3639]
Hi,
I'm trying to paginate the results of my scopes, but it only applies to the default scope (:all). The other scopes have too much items in it and it renders a TimeOutError because it cannot load them all.

I'm on RoR7, ruby 3.0.4 and using gems:
- Kaminari (1.2.2)
- Rails-admin (3.1.2)

Here is the code i expected to paginate all the scopes, but that did only for the default one:
![image](https://github.com/railsadminteam/rails_admin/assets/90650411/a0fca607-42fb-486f-a440-366e19b6fb9e)

I also tried to replace/add line limited_pagination without success.

**Comment by mshibuya** [comment]
I can't reproduce. What's in the `:with_current_tenant` implementation for example?

**Comment by mshibuya** [comment]
Please ping me on update.
