### ISSUE TITLE
Issue to work on local using importmap

### ISSUE THREAD

**Issue by sebfie** [railsadminteam/rails_admin#3640]
**Describe the bug**
I installed a fresh rails 7 app with rails admin. 

2 issues : 
- My local rails_admin.js is not used
- When adding a custom file like cocolis_rails_admin.js
- If I modify this js file, it does a 404 on asset pipeline due to the importmaping not refreshed even after a reload

**Expected behavior**
Reload js

**Additional context**

- `rails` version: 7
- `rails_admin` version: 3

**Comment by mshibuya** [comment]
Could you be more specific, like providing the actual steps you took starting from `rails new` ?

**Comment by mshibuya** [comment]
Please ping me on update.
