### ISSUE TITLE
Ability to prevent thumbnails for attachments

### ISSUE THREAD

**Issue by meeoh** [railsadminteam/rails_admin#3646]
**Is your feature request related to a problem? Please describe.**
I have a  model that `has_many_attached` some files. Those files are also encrypted. When an image is uploaded to that field and `rails_admin` tries to display the thumbnail, its using the `resize` variant which throws an error for encrypted files.

**Describe proposed solution(s)**
The ability to prevent images trying to be displayed for a certain field. If I can override `image?` or `resource_url` in the `ActiveStorageAttachment` class [here](https://github.com/railsadminteam/rails_admin/blob/0e12e5b465997c14d5b7a4d500a0d4cebed21aa9/lib/rails_admin/config/fields/types/multiple_active_storage.rb#L4) that would allow me to disable showing images at all for this field and instead just show text which links to the document

**Comment by mshibuya** [comment]
Simply:

```ruby
    field :encrypted_file, :multiple_active_storage do
      attachment do
        image false
      end
    end
```
