### ISSUE TITLE
Integration with Tailwind CSS for Styles

### ISSUE THREAD

**Issue by thisisrishabh22** [railsadminteam/rails_admin#3653]
**Is your feature request related to a problem? Please describe.**

As the current styling framework used in Rails Admin is Bootstrap which might not align with the preferences or needs of some users. Integrating Tailwind CSS as an option for styling would provide more flexibility and suffice to a wider range of user preferences. Even while using tailwind css for Application styling and using Rails Admin Engine for Admin Dashboard. `SassC` disrupts the compiling of assets. Although this has the work around as [mentioned](https://github.com/railsadminteam/rails_admin/issues/3450). I would like to know if there's any plans currently or in future to have Tailwind CSS for styling the views.

**Describe proposed solution(s)**

Integrating Tailwind CSS into Rails Admin to offer it as an alternative styling framework. This might involve the following steps:

1. Incorporate Tailwind CSS into `rails_admin`.
2. Add extra views if Tailwind is used in the Application for styling, ensuring that it seamlessly blends with the Rails Admin interface.
3. The CSS `processor` can be detected like `asset_source` is being detected.

**Additional context**
N/A

**Comment by mshibuya** [comment]
Currently there's no plan for moving away from Bootstrap. Also I don't think it's realistic to add the Tailwind support as an alternative choice, as it will increase the maintenance overhead greatly.
