### ISSUE TITLE
Navbar Garbled on rails_admin 3.1.x

### ISSUE THREAD

**Issue by jonmchan** [railsadminteam/rails_admin#3658]
**Describe the bug**
The navigation bar on the left hand side is all jumbled after upgrading to rails_admin 3.1.2. It worked fine on rails_admin 3.0.0.

**Reproduction steps**
Upgraded from rails_admin 3.0.0 to 3.1.2.

I'm on rails 7 using sprockets.

**Expected behavior**

Sidebar not to be garbled up.

**Additional context**

On rails_admin 3.0.0:
![image](https://github.com/railsadminteam/rails_admin/assets/1827190/d2670818-1624-448b-8af8-9da137695113)

On rails_admin 3.1.2:

![image](https://github.com/railsadminteam/rails_admin/assets/1827190/2912af55-f281-4818-9124-e7173c03df97)

Tried it also on rails_admin 3.1.0. I see the same issue.

**Comment by mshibuya** [comment]
It is highly likely that you're using the old CSS from RailsAdmin 3.0.0. How do you build your RailsAdmin assets?

**Comment by jonmchan** [comment]
@mshibuya thanks for your reply - doing a `rake assets:clobber` after `bundle update` did the trick.
