### ISSUE TITLE
Cannot hide the select box in a `has_one` field

### ISSUE THREAD

**Issue by vpereira** [railsadminteam/rails_admin#3667]
Hello RailsAdminTeam!

I'm having some issues trying to remove the select box from a form for a model with a `has_one` present

I have two models:

```
Class Repository
  has_one :tag_filter

  edit do
   field :tag_filter do
     inline_edit false
     inline_add false
     formatted_value do
            bindings[:view].link_to 'Edit Tag Filter',
                                    bindings[:view].rails_admin.edit_path(:tag_filter, bindings[:object].tag_filter.try(:id))
     end
   end
  end
```

```
Class TagFilter
  belongs_to :repository
```

What I'm trying to achieve:

![Screenshot from 2024-01-09 15-53-33](https://github.com/railsadminteam/rails_admin/assets/37418/ddaa62b4-7bc5-405b-888d-e48f5d8f5b03)

(just worked when passing a partial to the field, but then somehow I cannot trigger the modals correctly)

What I have today:

![Screenshot from 2024-01-09 15-52-20](https://github.com/railsadminteam/rails_admin/assets/37418/7b06c0e6-20e7-4d67-aee4-802997741a88)

There is any solution for that? I want to avoid users mistakenly connecting their repository with a wrong tag_filter, but I'm not sure how to make it work.

**Comment by mshibuya** [comment]
There can be several ways to achieve this, and one solution is:

```ruby
   field :tag_filter do
     read_only true
     formatted_value do
            bindings[:view].link_to 'Edit Tag Filter',
                                    bindings[:view].rails_admin.edit_path(:tag_filter, bindings[:object].tag_filter.try(:id)),
                                    {class: 'btn btn-info'}
     end
   end
```
