### ISSUE TITLE
Ruby 3.4.0 will drop csv from its default gems

### ISSUE THREAD

**Issue by vpereira** [railsadminteam/rails_admin#3682]
Running rails_admin with ruby 3.3.1 I am getting the following warning:

```
/home/foo/.bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30: warning: /usr/lib64/ruby/3.3.0/csv.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of rails_admin-3.1.2 to add csv into its gemspec.
```
So i guess rails admin should add the `csv` gem to the gemspec?

**Comment by pcai** [comment]
looks like this made it into main earlier this year, https://github.com/railsadminteam/rails_admin/blob/master/rails_admin.gemspec#L10 but there hasnt been a release with the update yet.

**Comment by mshibuya** [comment]
Right. Please use v3.2.0.beta or later.
