### ISSUE TITLE
Override/extend controller

### ISSUE THREAD

**Issue by sumanmukherjee03** [railsadminteam/rails_admin#483]
Due to certain circumstances (mostly related to polymorphic model management), I would like to extend one of rails admin controller to add an extra validation before saving the models, but currently I cannot do that because as soon as I use the following code in the initializer, the gem would no longer recognize the controller:

```
module RailsAdmin
  class MainController < RailsAdmin::ApplicationController
  end
end

Can I get some guidance?
```

**Comment by fercreek** [comment]
@michaek where did you put this file?

**Comment by michaek** [comment]
It's been a while, but I believe I may have had that as an initializer, in the `config/initializers` directory.
