### ISSUE TITLE
Redirect loop when visiting /admin

### ISSUE THREAD

**Issue by andypike** [railsadminteam/rails_admin#715]
Hi all,

I've just installed rails_admin for the first time and have hit a bit of a snag. After installation I go to /admin and I end up in a redirection loop. When Chrome displays the error the url in the address bar is: /admin_users/sign_in

Firstly, during the install I had a problem with Devise. I think the `gem 'devise'` line was added to the end of my gemfile but without a new line and so it was appended to and closing block `end` (eg: `endgem 'devise'`) which caused problems for the rails_admin install process. I got through that and updated devise manually afterwards.

I'm also user a custom user model of `admin_user` as I already have a user model that I don't want to allow access to rails_admin.

I haven't done any other customization from the default install. But I get the redirection loop if I go to /admin. I've checked over everything and it all looks good (as far as I can tell).

I can get it to work if I edit the rails_admin initializer to include an empty `config.authenticate_with` block. But of course this means there isn't any authentication and anyone can see the admin panel.

Any ideas to point me in the right direction? This might be related to the failed initial install but I think I covered everything.

Thanks in advance

Andy

**Comment by kidlab** [comment]
Yeah, I got this problem too. @iRonin's solution works! Thank you.
