### ISSUE TITLE
Where to define my CSS

### ISSUE THREAD

**Issue by samdebutcha** [railsadminteam/rails_admin#738]
In readme "Fields - Column CSS class"

<pre>config.model Team do
    list do
      field :name
      field :created_at do
        css_class "customClass"
      end
    end
  end
</pre>

where I should define customClass, except the hook:

<pre>
before_filter :if => Proc.new{ |c| c.request.path =~ /admin/ } do
    @head_stylesheet_paths = ['rails_admin_custom.css']
end
</pre>

**Comment by u007** [comment]
ive followed dmilisic configuration,
and setting this seems to does the trick even in development environment

Rails.application.config.assets.version = '1.1'

**Comment by commodoretyler** [comment]
Clearing tmp/cache and restarting the server worked for me as well. This really should be in the docs.
