### ISSUE TITLE
The initializer if forcing the :en locale (reopen #187)

### ISSUE THREAD

**Issue by jbescoyez** [railsadminteam/rails_admin#746]
It seems the exact same issue as [#187](https://github.com/sferik/rails_admin/issues/187) has reappeared in edge.

The only workaround I found until now is to define `config.i18n.locale = :fr # your locale` in `application.rb`.

**Comment by x-ji** [comment]
Also not working for me. Still getting `I18n::InvalidLocale - :en is not a valid locale` error even after adding that line
