### ISSUE TITLE
Foreign key field displaying ID only and not the field name in rails_admin

### ISSUE THREAD

**Issue by chandanrekhi** [railsadminteam/rails_admin#845]
I have 4 models in my rails application, HQ, Area, Employee, Dealer and all are associated to each other as follows:-

Area belongs_to HQ, HQ has_many areas Employee belongs_to Area, Area has_many Employees Dealer belongs_to Area, Area has_many Dealers

I am using rails_admin to manage all the data. When I create a new Area and select its relevant HQ, the HQ name is displayed in the dropdown list as per the belongs_to association, but when I try to create new Employee or Dealer, the dropdown list for selecting the area shows only the Area ID like Area #1, Area #2 etc., and not its name like A,B,C. Also, when I click on a particular Area name to view its details in rails_admin, the header displays the text, Displaying details for Area "Area #1".

Please guide me, how to fix this issue.

**Comment by TheBrockEllis** [comment]
I know this is an old question, but I was running into the same problem and solved it. Figured folks may run into this again in the future.

The foreign key table must have a `name` column. If there is no `name` just the ID # will be displayed. Not sure if other fields like `title` would work, but I know for sure fields like `first_name` or `last_name` do NOT work.

Hope that helps someone else out in the future. ⛑
