### ISSUE TITLE
Can't access rails admin because of too many redirects

### ISSUE THREAD

**Issue by drale2k** [railsadminteam/rails_admin#942]
hey, i just installed Rails Admin but i can't access the backend.

When i go to /admin it redirects to/admin_users/sign_in (i chose 'admin_users' instead of 'users' in the setup) Safari tells me: _Could not open the page, too many redirects_

**Comment by nardonykolyszyn** [comment]
> Changing your routing configuration so that `devise_for` comes before `mount` of RailsAdmin, like:
> 
> ```ruby
>   devise_for :admin_users
>   mount RailsAdmin::Engine => '/', :as => 'rails_admin'
> ```
> 
> should also work.

This is not part of the official documentation, thank you, you saved me.
